<div class="header-left"></div>
<div class="header-right">
    <nav class="navbar navbar-light navbar-expand-sm">
        <div class="navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link toolbar" href="javascript:history.go(-1)" data-toggle="tooltip" data-original-title="Go Back">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link toolbar" href="javascript:history.forward()" data-toggle="tooltip" data-original-title="Go Forward">
                        <i class="fas fa-arrow-right"></i>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link toolbar" href="javascript:location.reload()" data-toggle="tooltip" data-original-title="Reload">
                        <i class="fas fa-sync-alt"></i>
                    </a>
                </li>
            </ul>

            <div class="d-md-block d-none">
                <?=$page->breadcrumb?>
            </div>

            <ul class="navbar-nav ml-auto">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle remove-caret" href="#" id="dropdownNotif" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-bell"></i>
                        <span class="notify"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-xl py-0" aria-labelledby="dropdownNotif">
                        <div class="dropdown-item-header">
                            <span><?= language('NOTIFICATIONS')?> (<?php echo $notifications->count(); ?>)</span>
                            <a href="#" class="text-primary">Mark all as read</a>
                        </div>
                        <div class="dropdown-item-list perfect-scrollbar position-relative">
                            <?php foreach($notifications as $notification): ?>
                                <a href="<?php echo $notification->hyperlink_url; ?>" class="dropdown-item unread">
                                    <div class="media">
                                        <div class="avatar avatar-40 mr-3">
                                            <img src="<?php echo $notification->sender->profile->avatar_url; ?>" alt="<?php echo $notification->sender->profile->fullname; ?>">
                                        </div>
                                        <div class="media-body">
                                            <p class="mb-0">
                                                <strong><?php echo $notification->sender->profile->fullname; ?></strong> <br>
                                                <?php echo $notification->message; ?>
                                            </p>
                                            <small><?php echo string_time_elapsed($notification->timestamp); ?></small>
                                        </div>
                                    </div>
                                </a>
                            <?php endforeach; ?>
                        </div>
                        <a href="<?php echo base_url('system/users/notifications'); ?>" class="dropdown-item dropdown-item-footer bg-white text-primary">
                            <?= language('VIEW_ALL')?>
                        </a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownUser" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="avatar">
                            <img src="<?php echo session()->account->profile->avatar_url ?? 'http://localhost:8000/assets/img/logo/logo.png'; ?>" alt="<?php echo session()->account->profile->fullname; ?>">
                        </div>
                        <span>
                            <?php echo session()->account->profile->fullname; ?>
                        </span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUser">
                        <a class="dropdown-item" href="<?= base_url('system/settings/users/form/' . session()->account->id) ?>">
                            <i class="fas fa-cog"></i> <?= language('BTN_SETTINGS')?></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?= base_url('logout') ?>">
                            <i class="fas fa-power-off"></i>
                            <?= language('BTN_LOGOUT')?>
                        </a>
                    </div>
                </li>

            </ul>
        </div>
    </nav>
</div>
