<div class="sidebar-menu">
	<ul>
		<li>
			<a href="<?=base_url('dashboard');?>">
				<span>
					<i class="fas fa-tachometer-alt"></i> <span class="hide">Dashboard</span></span>
				</span>
			</a>
		</li>
		<li class="menu-title">
			Personal
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('personal/notes'); ?>">
					<span>
						<i class="fas fa-align-left"></i> <span class="hide">Notes</span></span>
					</span>
				</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('personal/settings'); ?>">
					<span>
						<i class="fas fa-cog"></i> <span class="hide">Personal Settings</span></span>
					</span>
				</a>
			</div>
		</li>
		<li class="menu-title">
			Manage
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('pages'); ?>">
					<span>
						<i class="fas fa-file-alt"></i> <span class="hide">Site Pages</span></span>
					</span>
				</a>
				<a class="sidebar-button" href="<?php echo base_url('pages/form'); ?>">Add</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('media'); ?>">
					<span>
						<i class="fas fa-image"></i> <span class="hide">Media</span></span>
					</span>
				</a>
			</div>
		</li>

		<li class="menu-title">
			Administrator
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('administrator/users/management'); ?>">
					<span>
						<i class="fas fa-user-cog"></i> <span class="hide">Users Management</span></span>
					</span>
				</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('administrator/users/group'); ?>">
					<span>
						<i class="fas fa-users-cog"></i> <span class="hide">Users Group Management</span></span>
					</span>
				</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('administrator/package-manager'); ?>">
					<span>
						<i class="fas fa-users-cog"></i> <span class="hide">Module Installer</span></span>
					</span>
				</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('administrator/appearance'); ?>">
					<span>
						<i class="fas fa-palette"></i> <span class="hide">Appearance</span></span>
					</span>
				</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('administrator/settings'); ?>">
					<span>
						<i class="fas fa-cogs"></i> <span class="hide">Application Settings</span></span>
					</span>
				</a>
			</div>
		</li>
	</ul>
</div>
