<!-- Sidebar scroll-->
<div class="scroll-sidebar perfect-scrollbar">
    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
        <ul id="sidebarnav">
            <li class="sidebar-item">
                <a class="sidebar-link" href="<?=base_url('dashboard');?>">
                    <i class="fas fa-tachometer-alt"></i>
                    <span class="hide-menu">Dashboard</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a href="<?=base_url('testimonials');?>" class="sidebar-link">
                    <i class="fas fa-comments"></i>
                    <span class="hide-menu">Testimonials</span>
                </a>
            </li>

            <li class="nav-small-cap">
                <i class="fas fa-cubes"></i>
                <span class="hide-menu">Site</span>
            </li>

            <li class="sidebar-item">
                <a href="<?=base_url('site/page');?>" class="sidebar-link">
                    <i class="fas fa-file-alt"></i>
                    <span class="hide-menu">Pages</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a href="<?=base_url('site/posts');?>" class="sidebar-link">
                    <i class="fas fa-align-left"></i>
                    <span class="hide-menu">Posts</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a href="<?=base_url('site/media');?>" class="sidebar-link">
                    <i class="fas fa-image"></i>
                    <span class="hide-menu">Media</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a class="sidebar-link has-arrow" href="javascript:void(0)" aria-expanded="false">
                    <i class="fas fa-palette"></i>
                    <span class="hide-menu">Appearance</span>
                </a>

                <ul aria-expanded="false" class="collapse second-level">
                    <li class="sidebar-item">
                        <a href="<?=base_url('site/appearance/customize');?>" class="sidebar-link">
                            <i class="fas fa-swatchbook"></i>
                            <span class="hide-menu">Customize</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="<?=base_url('site/appearance/sliders');?>" class="sidebar-link">
                            <i class="fas fa-images"></i>
                            <span class="hide-menu">Sliders</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="<?=base_url('site/appearance/themes');?>" class="sidebar-link">
                            <i class="fas fa-paint-brush"></i>
                            <span class="hide-menu">Themes</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="sidebar-item">
                <a href="<?=base_url('site/settings');?>" class="sidebar-link">
                    <i class="fas fa-cog"></i>
                    <span class="hide-menu">Settings</span>
                </a>
            </li>

            <li class="nav-small-cap">
                <i class="fas fa-cubes"></i>
                <span class="hide-menu">System</span>
            </li>

            <li class="sidebar-item">
                <a class="sidebar-link has-arrow" href="javascript:void(0)" aria-expanded="false">
                    <i class="fas fa-server"></i>
                    <span class="hide-menu">System</span>
                </a>
                <ul aria-expanded="false" class="collapse first-level">
                    <li class="sidebar-item">
                        <a href="<?=base_url('system/information');?>" class="sidebar-link">
                            <i class="fas fa-info-circle"></i>
                            <span class="hide-menu">Information</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="<?=base_url('system/modules');?>" class="sidebar-link">
                            <i class="fas fa-cubes"></i>
                            <span class="hide-menu">Modules</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" href="<?=base_url('system/settings');?>" aria-expanded="false">
                            <i class="fas fa-cog"></i>
                            <span class="hide-menu">Settings</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow" href="javascript:void(0)" aria-expanded="false">
                            <i class="fas fa-users-cog"></i>
                            <span class="hide-menu">Users</span>
                        </a>

                        <ul aria-expanded="false" class="collapse second-level">
                            <li class="sidebar-item">
                                <a href="<?=base_url('system/users/manage');?>" class="sidebar-link">
                                    <i class="fas fa-users"></i>
                                    <span class="hide-menu">Manage</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a href="<?=base_url('system/users/roles');?>" class="sidebar-link">
                                    <i class="fas fa-user-shield"></i>
                                    <span class="hide-menu">Roles</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="sidebar-item">
                        <a href="<?=base_url('system/themes');?>" class="sidebar-link">
                            <i class="fas fa-paint-brush"></i>
                            <span class="hide-menu">Themes</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</div>
