<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-lg-4 col-md-6">
			<div class="card">
				<div class="card-body">
					<div class="logo text-center">
						<a href="javascript:void(0);">
							<img src="assets/img/logo/logo-rectangle-color.png">
						</a>
					</div>
					<form action="<?=base_url('login/authenticate');?>" method="post">
						<input type="hidden" name="csrfToken" value="">
						<div class="form-group">
							<label for="username">Username</label>
							<input type="text" class="form-control" name="username" id="username" placeholder="Enter username">
						</div>
						<div class="form-group">
							<label for="userpassword">Password</label>
							<input type="password" class="form-control" name="password" id="userpassword" placeholder="Enter password">
						</div>

						<div class="row align-items-center">
							<div class="col-sm-6">
								<div class="form-group">
									<div class="custom-control custom-checkbox">
										<input type="checkbox" class="custom-control-input" id="customControlInline">
										<label class="custom-control-label" for="customControlInline">Remember me</label>
									</div>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="form-group text-right">
									<button class="btn btn-primary" type="submit">Log In</button>
								</div>
							</div>
						</div>
						<div class="form-group text-center">
							<a href="javascript:void(0);" class="text-muted">
								<i class="fas fa-lock"></i> Forgot your password?
							</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>