<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">    
                            <ul class="nav">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#">Published</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Drafts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Trash</a>
                                </li>
                            </ul>

                            <form class="nav-search">
                                <div class="search-icon open-search">
                                    <i class="fas fa-search"></i>
                                </div>
                                <div class="search-input">
                                    <input type="search" placeholder="Search...">
                                </div>
                                <div class="search-icon close-search">
                                    <i class="fas fa-times"></i>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" value="http://example.com/action" name="dropzone-url">
        <div class="media-list">
            <div class="dropzone-form" style="cursor: pointer;">
                <div class="dz-message needsclick">
                    <p>Drop files here or click to upload.<br>
                        <span class="note needsclick">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span></p>
                </div>
                <div class="dropzone-previews" id="dropzone-previews">
                    <div class="dz-template" id="dropzone-preview">
                        <div class="media-list-item uploading">
                            <div class="media-list-action d-flex">
                                <button type="button" class="btn btn-info btn-xs btn-edit mr-2" data-toggle="modal" data-target="#modal-edit">Edit</button>
                                <button type="button" class="btn btn-danger btn-xs">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </div>

                            <div class="media-item">
                                <img data-dz-thumbnail>
                                <div class="media-item-file-details">
                                    <div class="media-item-icon">
                                        <i class="fas fa-file-powerpoint"></i>
                                    </div>
                                    <div class="media-item-file-name" data-dz-name></div>
                                    <div class="media-item-file-extension"></div>
                                </div>
                            </div>

                            <div class="upload-progress">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 0%" data-dz-uploadprogress></div>
                                </div>
                            </div>

                            <div class="media-item-file-error">
                                <div class="media-item-icon-error">
                                    <i class="fas fa-exclamation-circle"></i>
                                </div>
                                <div class="media-item-file-name-error" data-dz-errormessage></div>
                                <div class="media-item-file-extension-error d-flex justify-content-center">
                                    <button type="button" class="btn btn-outline-light btn-sm" data-dz-remove>
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
	    <div class="row">
            <div class="col-md-12">
                <nav>
                    <ul class="pagination d-flex justify-content-center">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>
            </div>
        </div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade modal-scroll" id="modal-edit" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalEdit" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <form>
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEdit">Media Edit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="media-editor-wrapper">
                                <img src="assets/img/cover.jpg">
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" class="form-control" name="">
                            </div>
                            <div class="form-group">
                                <label>Caption</label>
                                <textarea class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label>Alt Text</label>
                                <input type="text" class="form-control" name="">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label>URL</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" readonly="">
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-default">Copy</button>
                                    </div>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table file-info">
                                    <tr>
                                        <td width="50%" class="border-0">
                                            <span class="text-muted">File Name</span><br>
                                            bank.jpg
                                        </td>
                                        <td class="border-0">
                                            <span class="text-muted">File Type</span><br>
                                            JPG
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="border-0">
                                            <span class="text-muted">File Dimensions</span><br>
                                            1366 x 1454px
                                        </td>
                                        <td class="border-0">
                                            <span class="text-muted">Upload Date</span><br>
                                            17 April 2018
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
