<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <!-- <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">
                            <ul class="nav" id="administratorTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#authorities" role="tab" aria-selected="true"> <?php echo $language->getLine('AUTHORITIES'); ?></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="#settings" role="tab" aria-selected="false"><?php echo $language->getLine('SETTINGS'); ?></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div> -->

                <?php if($profile = $user->profile):?>
                    <div class="row justify-content-center pb-5 pt-3">
                        <div class="col-lg-12 d-flex justify-content-center">
                            <div class="media">
                                <a href="<?=$profile->avatar;?>">
                                    <img class="d-flex mr-3 rounded-circle" src="<?=$profile->avatar;?>" alt="<?=$profile->name;?>" width="80" height="80">
                                </a>
                                <div class="media-body">
                                    <div class="mb-1 d-flex align-items-center">
                                        <button class="btn btn-default btn-xs mr-1">@<?=$user->username;?></button>
                                        <a href="<?=base_url('administrator/detail/'.$user->id);?>"> <?=$profile->name;?> </a>
                                        <?php if(services('user')->hasWriteAccess()): ?>
                                            <div class="dropdown ml-2">
                                                <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                    <a class="dropdown-item" href="<?=base_url('administrator/form/'.$user->id);?>"> <i class="fas fa-pencil-alt text-muted"></i> <?php echo $language->getLine('BTN_EDIT'); ?> </a>
                                                    <div class="dropdown-divider"></div>
                                                    <a class="dropdown-item" href="<?=base_url('administrator/delete/'.$user->id);?>" data-action="delete" data-id="1"> <i class="fa fa-trash text-muted"></i> <?php echo $language->getLine('BTN_DELETE'); ?> </a>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <span class="btn btn-xs btn-default"><?=$profile->birthplace;?>, <?=date('d , M Y', strtotime($profile->birthday));?></span>
                                    <span class="btn btn-xs btn-default btn-icon">
                                    <?php if($profile->gender === 'MALE'):?>
                                    <i class="fa fa-mars"></i> <?=$profile->gender;?> </span>
                                    <?php else:?>
                                        <i class="fa fa-venus"></i> <?=$profile->gender;?> </span>
                                    <?php endif;?>
                                    <span class="btn btn-xs btn-default"><?=$profile->marital;?></span>
                                    <span class="btn btn-xs btn-default"><?=$profile->religion;?></span>
                                    <div class="d-block mt-1 mb-2">
                                        <a href="mailto:steeven@webit.id" class="btn btn-xs btn-default btn-icon"> <i class="fa fa-envelope"></i><?=$user->email;?> </a>
                                        <a href="tel:082117490099" class="btn btn-xs btn-default btn-icon"> <i class="fa fa-phone"></i> <?=$user->msisdn;?> </a>
                                    </div>
                                    <blockquote>
                                        <p><?=$profile->biography;?></p>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif;?>

                <?php $user = $user->moduleUser;?>
                <div class="tab-content border-0 p-0">
                    <div class="tab-pane fade show active" id="authorities" role="tabpanel">
                        <div class="card">
                            <div class="card-header d-flex align-items-center justify-content-between">
                                <h5 class="mb-0"><?php echo $language->getLine('AUTHORITIES'); ?></h5>
                            </div>
                        </div>
                        <div class="row">
                            <?php if($module):?>
                                <div class="col-md-12">
                                    <div class="card">
                                        <div class="card-body with-table">
                                            <div class="accordion">
                                                <div class="">
                                                    <table class="table table-bordered">
                                                        <thead>
                                                        <tr>
                                                            <th colspan="3"><?=language('CONTROLLERS')?></th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        <?php $key = 0;?>
                                                        <?php if($module->controllers): ?>
                                                        <?php foreach($module->controllers as $className => $methods): ?>
                                                        <tr>
                                                            <td colspan="3">
                                                                <a href="#controller-<?=md5($className)?>" data-toggle="collapse" aria-expanded="false">
                                                                    <?=$className?>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                        <?php if(count($methods)): ?>
                                                        <tbody id="controller-<?=md5($className)?>" class="collapse">
                                                        <tr>
                                                            <th width="30%"><?=language('METHODS')?></th>
                                                            <th width="30%"><?=language('ROLES')?></th>
                                                        </tr>
                                                        <?php foreach($methods as $method): ?>
                                                            <tr>
                                                                <td><?=$method->name?></td>
                                                                <td>
                                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                                        <span><?=$language->getLine('PERMISSION')?></span>
                                                                        <div class="three-state-switch">
                                                                            <input class="insert-user" data-user="<?=$user->id;?>" data-segment="<?=$method->id;?>" data-permission="DENIED" type="radio" name="role[<?=$key;?>]" id="denied-<?=$key;?>"
                                                                                <?php if($method->users):?>
                                                                                    <?php foreach ($method->users as $methodRole):?>
                                                                                        <?php if($methodRole->id_sys_module_user == $user->id):?>
                                                                                            <?php if($methodRole->permission == 'DENIED'):?>
                                                                                                checked
                                                                                            <?php endif;?>
                                                                                        <?php endif;?>
                                                                                    <?php endforeach;?>
                                                                                <?php endif;?>
                                                                            >
                                                                            <label for="denied-<?=$key;?>" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                                <span><i class="fas fa-ban"></i></span>
                                                                            </label>

                                                                            <input
                                                                                <?php if($method->users):?>
                                                                                    <?php foreach ($method->users as $methodRole):?>
                                                                                        <?php if($methodRole->id_sys_module_user == $user->id):?>
                                                                                            <?php if($methodRole->permission == 'GRANTED'):?>
                                                                                                checked
                                                                                            <?php endif;?>
                                                                                        <?php endif;?>
                                                                                    <?php endforeach;?>
                                                                                <?php endif;?>
                                                                                    class="insert-user" data-user="<?=$user->id;?>" data-segment="<?=$method->id;?>" data-permission="GRANTED" type="radio" name="role[<?=$key;?>]" id="GRANTED-<?=$key;?>" value="2">
                                                                            <label for="GRANTED-<?=$key;?>" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                                <span><i class="fas fa-eye"></i></span>
                                                                            </label>
    
                                                                            <input   <?php if($method->users):?>
                                                                                <?php foreach ($method->users as $methodRole):?>
                                                                                    <?php if($methodRole->id_sys_module_user === $user->id):?>
                                                                                        <?php if($methodRole->permission == 'WRITE'):?>
                                                                                            checked
                                                                                        <?php endif;?>
                                                                                    <?php endif;?>
                                                                                <?php endforeach;?>
                                                                            <?php endif;?>
                                                                                    class="insert-user" data-user="<?=$user->id;?>" data-segment="<?=$method->id;?>" data-permission="WRITE" type="radio" name="role[<?=$key;?>]" id="write-<?=$key;?>" value="3">
                                                                            <?php if(services('user')->hasWriteAccess()): ?>
                                                                                <label for="write-<?=$key;?>" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                                    <span><i class="fas fa-pencil-alt"></i></span>
                                                                                </label>
                                                                            <?php endif; ?>
                                                                        </div>
                                                                    </div>
                                                                </td>
                                                            </tr>
                                                            <?php $key++;?>
                                                        <?php endforeach; ?>
                                                        </tbody>
                                                        <?php endif; ?>
                                                        <?php endforeach; ?>
                                                        <?php endif; ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php else:?>
                                <?php if($modules):?>
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-body with-table">
                                                <div class="table-responsive">
                                                    <table class="table table-striped valign-middle">
                                                        <thead>
                                                        <tr>
                                                            <th><?=language('NAMESPACE')?></th>
                                                            <th><?=language('TYPE')?></th>
                                                            <th></th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        <?php foreach($modules as $module): ?>
                                                            <tr>
                                                                <td>
                                                                    <a href="<?=base_url('administrator/detail/' . $user->id,['id_segment'=>$module->id]); ?>">
                                                                        <?php echo str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;', $module->record_depth); ?>
                                                                        <?php echo ($module->record_depth == 0 ? '' : '&#8627;'); ?>
    
                                                                        <?=$module->namespace?>
                                                                    </a>
                                                                </td>
                                                                <td>
                                                                    <span class="text-uppercase badge badge-info"><?=$module->type?></span>
                                                                </td>
                                                                <td>
                                                                    <div class="btn-group btn-group-sm">
                                                                        <a class="btn btn-default btn-sm" href="<?=base_url('administrator/modules/form/' . $module->id); ?>">
                                                                            <i class="fas fa-edit"></i>
                                                                        </a>
                                                                        <a class="btn btn-default btn-sm" href="<?=base_url('administrator/modules/delete/' . $module->id); ?>" data-action="delete">
                                                                            <i class="fa fa-trash"></i>
                                                                        </a>
                                                                    </div>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach;?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                <?php else:?>
                                    <div class="col-lg-12 text-center p-3">
                                        <img src="{{storage_url('images/default/no-departments-image.png')}}" class="img-fluid">
                                        <h3 class="mt-3"><?php echo $language->getLine('ALERT_DATA_EMPTY_HEADING'); ?></h3>
                                        <h6 class="text-danger mb-4">
                                            <?php echo $language->getLine('ALERT_DATA_EMPTY_MESSAGE'); ?>
                                        </h6>
                                    </div>
                                <?php endif;?>
                            <?php endif;?>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>