<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <div class="card">
                <div class="card-body p-0">
                    <div class="nav-pages">    
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link active" href="#">Published</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Drafts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Trash</a>
                            </li>
                        </ul>

                        <form class="nav-search">
                            <div class="search-icon open-search">
                                <i class="fas fa-search"></i>
                            </div>
                            <div class="search-input">
                                <input type="search" placeholder="Search...">
                            </div>
                            <div class="search-icon close-search">
                                <i class="fas fa-times"></i>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="user-list">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="card">
                    <h5 class="card-header d-flex justify-content-between align-items-center">
                        Users                        
                        <a href="<?php echo base_url('users-management/form'); ?>" class="btn btn-default btn-md"> Add New</a>
                    </h5>
                    <div class="card-body pb-0">
                        <div class="media align-items-center mb-4">
                            <div class="avatar">
                                <img src="assets/img/avatar.jpg" class="mr-3 rounded-circle" width="72" height="72">
                            </div> 
                            <div class="media-body d-flex align-items-center justify-content-between">
                                <div>
                                    <h1>
                                        <a href="#">Eddy Dharma</a>
                                    </h1>
                                    <h6>
                                        <span class="text-lowercase">@restumulya</span>
                                    </h6>
                                    <button class="btn btn-primary btn-xs btn-icon">
                                        <i class="fas fa-user-lock"></i> ADMINISTRATOR                                                    
                                    </button>
                                </div>
                                <div class="user-action">
                                    <div class="dropdown">
                                        <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="<?php echo base_url('pages/form'); ?>">
                                                <i class="fas fa-pencil-alt"></i>
                                                Edit
                                            </a>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-eye"></i>
                                                View
                                            </a>
                                            <a class="dropdown-item" href="#">
                                                <i class="fas fa-chart-bar"></i>
                                                Stats
                                            </a>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-copy"></i>
                                                Copy
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-trash"></i>
                                                Trash
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="media align-items-center mb-4">
                            <div class="avatar">
                                <img src="assets/img/avatar.jpg" class="mr-3 rounded-circle" width="72" height="72">
                            </div> 
                            <div class="media-body d-flex align-items-center justify-content-between">
                                <div>
                                    <h1>
                                        <a href="#">Tansil</a>
                                    </h1>
                                    <h6>
                                        <span class="text-lowercase">@tansil</span>
                                    </h6>
                                    <button class="btn btn-primary btn-xs btn-icon">
                                        <i class="fas fa-user-lock"></i> ADMINISTRATOR                                                    
                                    </button>
                                </div>
                                <div class="user-action">
                                    <div class="dropdown">
                                        <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="<?php echo base_url('pages/form'); ?>">
                                                <i class="fas fa-pencil-alt"></i>
                                                Edit
                                            </a>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-eye"></i>
                                                View
                                            </a>
                                            <a class="dropdown-item" href="#">
                                                <i class="fas fa-chart-bar"></i>
                                                Stats
                                            </a>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-copy"></i>
                                                Copy
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-trash"></i>
                                                Trash
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    <nav>
        <ul class="pagination d-flex justify-content-center">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>