<div class="page-dashboard">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-md-11">
                <div class="card">
                    <h5 class="card-header">
                        Statistik Minggu ini
                    </h5>
                    <div class="card-body">
                        <div class="row">
                            <!-- <div class="col-md-4">
                                <div class="row justify-content-between">
                                    <div class="col-md-auto">
                                        <h6>Skor Performa toko</h6>
                                    </div>
                                    <div class="col-md-auto">
                                        <h6>80/100</h6>
                                    </div>
                                </div>
                                <div class="progress rounded mb-4">
                                    <div class="progress-bar rounded" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                <p>
                                    Dengan poin minimum 75, tokomu siap upgrade menjadi Power Merchant.
                                </p>
                            </div> -->
                            <div class="col-md-8">
                                <div class="row">
                                    <!-- <div class="col-md-3 mb-4">
                                        <h6>Reguler Merchant</h6>
                                        <a href="#" class="btn btn-primary btn-sm">Upgrade Tokomu</a>
                                    </div> -->
                                    <!-- <div class="col-md-3 mb-4">
                                        <p>
                                            <i class="fas fa-medal"></i> 4.5<br>
                                            <small class="text-muted">(145 Poin)</small>
                                        </p>
                                    </div> -->
                                    <div class="col-md-3 mb-4">
                                        <p>
                                            <i class="fas fa-medal"></i> <?= $total_testimonials ?><br>
                                            <small class="text-muted">Ulasan</small>
                                        </p>
                                    </div>
                                    <div class="col-md-3 mb-4">
                                        <p>
                                            <i class="fas fa-users"></i> <?= $total_companies ?><br>
                                            <small class="text-muted">Companies</small>
                                        </p>
                                    </div>
                                </div>

                                <div class="row">
                                    <!-- <div class="col-md-3 mb-4">
                                        <p>
                                            <i class="fas fa-eye"></i> 1.289<br>
                                            <small class="text-muted">Pengunjung</small>
                                        </p>
                                    </div> -->
                                    <!-- <div class="col-md-3 mb-4">
                                        <p>
                                            <i class="fas fa-percentage"></i> 87%<br>
                                            <small class="text-muted">Presentase penjualan</small>
                                        </p>
                                    </div> -->
                                    <div class="col-md-3 mb-4">
                                        <p>
                                            <i class="fas fa-boxes"></i> <?= $total_sales ?><br>
                                            <small class="text-muted">Produk Terjual</small>
                                        </p>
                                    </div>
                                    <!-- <div class="col-md-3 mb-4">
                                        <p>
                                            <i class="fas fa-users"></i> Rp. 325K<br>
                                            <small class="text-muted">Pendapatan Kotor</small>
                                        </p>
                                    </div> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>