<div class="container-fluid">
	<div class="row justify-content-center">
        <div class="col-lg-4 col-md-6">
            <div class="card">
                <div class="card-body">
                    <div class="logo text-center">
                        <a href="javascript:void(0);">
                            <img src="assets/img/logo/logo-rectangle-color.png">
                        </a>
                    </div>
                    <div class="alert align-items-center d-none" role="alert">
                        <div class="alert-message"></div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">
								<i class="fas fa-times"></i>
							</span>
                        </button>
                    </div>
                    <form id="form-login" action="<?=base_url('login/authenticate');?>" method="post" class="needs-validation" novalidate>
                        <input type="hidden" name="csrf-token" value="{{$csrfToken}}">
                        <div class="form-group">
                            <label for="email">Enter your email</label>
                            <input type="email" class="form-control" name="email" id="email" placeholder="neon@o2system.id" required>
                            <div class="invalid-feedback">
                                Please input your a email.
                            </div>
                        </div>
                        <div class="form-group pt-2">
                            <button class="btn btn-primary btn-block" type="submit">
                                <span class="text" role="btn-text">Reset Password</span>
                                <span class="btn-loading d-none" role="btn-preloader">
									<span class="dot"></span>
									<span class="dot"></span>
									<span class="dot"></span>
								</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
	</div>
</div>