
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12">
            <?=view('settings/nav', [], true);?>
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">Master Data</h5>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="list-group mb-3">
                    <a href="<?=base_url('master/geodirectories');?>" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h6 class="mb-1">Geodirectories</h6>
                        </div>
                        <p class="mb-0 text-muted"> <span class="fa fa-tag"></span> <?= ($total_geodirectories ? $total_geodirectories : 0) ?> Geodirectories</p>
                    </a>
                    <a href="<?=base_url('master/banks');?>" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h6 class="mb-1">Banks</h6>
                        </div>
                        <p class="mb-0 text-muted"> <span class="fa fa-tag"></span> <?= ($total_banks ? $total_banks : 0) ?> Banks</p>
                    </a>
                    <a href="<?=base_url('master/currencies');?>" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h6 class="mb-1">Currencies</h6>
                        </div>
                        <p class="mb-0 text-muted"> <span class="fa fa-tag"></span> <?= ($total_currencies ? $total_currencies : 0) ?> Currencies</p>
                    </a>
                </div>
        </div>
    </div>
</div>