<form class="form-horizontal" id="form-login" action="{{base_url('forgot-password')}}" method="post">
    <a href="javascript:void(0)" class="text-center d-block">
        <img src="./assets/img/logo/logo-200px.png" alt="O2CMS" height="100"/>
    </a>

    <div class="form-group row mt-5">
        <?php if (session()->getFlash('success')): ?>
            <div class="col-md-12">
                <div class="alert alert-success">
                    <h4>Forgot Password</h4>
                    <p><?php echo session()->getFlash('success'); ?></p>
                </div>
            </div>
        <?php elseif (session()->getFlash('error')): ?>
            <div class="col-md-12">
                <div class="alert alert-danger">
                    <h4>Forgot Password</h4>
                    <p><?php echo session()->getFlash('error'); ?></p>
                </div>
            </div>
        <?php endif; ?>

        <div class="col-md-12">
            <div class="input-group mb-2 mb-sm-0">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                </div>
                <input name="username" type="text" class="form-control" id="input-username" placeholder="username@example.com">
            </div>
        </div>
    </div>
    <div class="form-group row text-center mt-4">
        <div class="col-md-12">
            <button class="btn btn-primary btn-block" type="submit">Reset Password</button>
        </div>
    </div>
</form>