<form class="form-horizontal" id="form-login" action="{{base_url('login/reset-password')}}" method="post">
    <a href="javascript:void(0)" class="text-center d-block">
        <img src="./assets/img/logo/logo-200px.png" alt="O2CMS" height="100"/>
    </a>

    <?php if (session()->getFlash('success')): ?>
        <div class="alert alert-success">
            <p><?php echo session()->getFlash('success'); ?></p>
        </div>
    <?php elseif (session()->getFlash('error')): ?>
        <div class="alert alert-danger">
            <p><?php echo session()->getFlash('error'); ?></p>
        </div>
    <?php endif; ?>

    <div class="form-group row mt-5">
        <div class="col-md-12">
            <div class="input-group mb-2 mb-sm-0">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-user"></i></span>
                </div>
                <input name="username" type="text" class="form-control" value="<?php echo $account->username; ?>" disabled>
            </div>
        </div>
        <div class="col-md-12">
            <div class="input-group mb-2 mb-sm-0">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-lock"></i></span>
                </div>
                <input name="password" type="password" class="form-control" placeholder="New Password">
                <input name="retype-password" type="password" class="form-control" placeholder="Re-type Password">
            </div>
        </div>
    </div>
    <div class="form-group row text-center">
        <div class="col-md-12">
            <button class="btn btn-primary btn-block" type="submit">Reset Password</button>
        </div>
    </div>
</form>