<div class="page-employee">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <?php if (null !== ($message = $session->getFlash('success'))): ?>
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">
                            <?php echo $language->getLine('ALERT_SUCCESS_HEADING'); ?>
                        </h4>
                        <p><?php echo $message; ?></p>
                    </div>
                <?php elseif (null !== ($message = $session->getFlash('danger'))): ?>
                    <div class="alert alert-danger" role="alert">
                        <h4 class="alert-heading">
                            <?php echo $language->getLine('ALERT_DANGER_HEADING'); ?>
                        </h4>
                        <p><?php echo $message; ?></p>
                    </div>
                <?php endif; ?>


                <div class="row align-items-center py-5">
                    <div class="col-lg-8">
                        <div class="media align-items-center">
                            <a href="<?php echo base_url('personal/profile/overview', ['id_employee' => $employee->id]); ?>">
                                <img class="d-flex mr-3 rounded-circle" src="<?php echo $employee->avatar; ?>" alt="<?php echo $employee->name; ?>" width="150" height="150">
                            </a>
                            <div class="media-body">
                                <div class="mb-0 d-flex align-items-center">
                                    <a href="<?php echo base_url('personal/profile/overview', ['id_employee' => $employee->id]); ?>" class="d-flex align-items-center">
                                        <span class="btn btn-default btn-xs mr-2"> <?php echo $employee->initial; ?></span>
                                        <?php echo $employee->name; ?>
                                    </a>
                                    <div class="dropdown ml-2">
                                        <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            <a class="dropdown-item" href="<?=base_url('personal/profile/form/'.$employee->id);?>">
                                                <i class="fas fa-pencil-alt text-muted"></i> <?php echo $language->getLine('BTN_EDIT'); ?>
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="<?=base_url('personal/profile/delete/'.$employee->id);?>" data-action="delete" data-id="1">
                                                <i class="fa fa-trash text-muted"></i> <?php echo $language->getLine('BTN_DELETE'); ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <?php if(is_object($employee->designation)):?>
                                    <p class="mb-2"> <?php echo $employee->designation->title; ?> &mdash; <a href="<?php echo base_url('company/departments/'); ?>"><?php echo  $employee->designation->department ? $employee->designation->department->name : ''; ?></a>
                                    </p>
                                <?php endif ;?>

                                <a href="#" class="btn btn-default btn-xs">@username</a>

                                <?php if ($employee->number_personnel): ?>
                                    <span class="btn btn-xs btn-default"> <?php echo $employee->number_personnel; ?></span>
                                <?php endif; ?>
                                <?php if ($employee->gender === 'MALE'): ?>
                                    <span class="btn btn-xs btn-default btn-icon">
                                        <i class="fa fa-venus"></i> <?php echo $language->getLine('MALE'); ?>
                                    </span>
                                <?php else : ?>
                                    <span class="btn btn-xs btn-default btn-icon">
                                        <i class="fa fa-mars"></i> <?php echo $language->getLine('FEMALE'); ?>
                                    </span>
                                <?php endif; ?>
                                <?php if ($employee->blood !== null): ?>
                                    <span class="btn btn-xs btn-danger btn-icon">
                                        <i class="fa fa-tint"></i>  <?php echo $employee->blood; ?>
                                    </span>
                                <?php endif; ?>
                                <span class="btn btn-xs btn-default"><?php echo $language->getLine($employee->marital); ?></span>
                                <div class="d-block mt-2">
                                    <?php if ($employee->email !== null): ?>
                                        <a href="mailto:<?php echo $employee->email->address; ?>" class="btn btn-xs btn-default btn-icon">
                                            <i class="fa fa-envelope"></i> <?php echo $employee->email->address; ?>
                                        </a>
                                    <?php endif; ?>

                                    <?php if ($employee->mobile !== null): ?>
                                        <a href="tel:<?php echo $employee->mobile->number; ?>" class="btn btn-xs btn-default btn-icon">
                                            <i class="fa fa-phone"></i> <?php echo $employee->mobile->number; ?>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 text-center">
                        <span class="btn btn-default btn-block mb-1">  <?php echo $employee->tenure; ?></span>
                        <small class="text-muted mb-0"> <?php echo $language->getLine('SINCE'); ?>
                            : <?php echo $employee->date_join; ?>
                        </small>
                        <?php if ($employee->employment === 'RESIGN'): ?>
                            <span class="btn btn-danger btn-block mt-2 mb-1">
                                        <?php echo $language->getLine($employee->employment); ?>
                                    </span>
                            <small class="text-muted mb-0">
                                <?php echo $language->getLine('SINCE'); ?>
                                : <?php echo $employee->date_resignation; ?>
                            </small>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="tab-content border-0 p-0">
                    <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('BIODATA'); ?>

                                                <a class="btn btn-primary btn-sm" data-modal="modal-form" href="<?php echo base_url('personal/profile/biodata/form', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_EDIT'); ?>
                                                </a>
                                            </h6>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('AGE'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $employee->age; ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('GENDER'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $language->getLine($employee->gender); ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('BLOOD_TYPE'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p> <?php if ($employee->rhesus): ?>
                                                            <?php if ($employee->rhesus == 'YES'): ?>
                                                                <?php echo '+'; ?>
                                                            <?php else: ?>
                                                                <?php echo '-'; ?>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                        <?php echo $employee->blood; ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('BIRTHPLACE'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $employee->birthplace; ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('BIRTHDAY'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $employee->birthday; ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('MARITAL'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $language->getLine($employee->marital); ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('RELIGION'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $language->getLine($employee->religion); ?></p>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="profile">
                                            <h6><?php echo $language->getLine('EYESIGHT_SYNDROME'); ?></h6>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('RIGHT_EYE'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <?php if ($employee->eyes): ?>
                                                        <p>
                                                            <?php echo $language->getLine($employee->eyes->sight_left); ?> <span class="badge badge-danger"> <?php echo $language->getLine($employee->eyes->value_left); ?></span>
                                                        </p>
                                                    <?php endif; ?>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('LEFT_EYE'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <?php if ($employee->eyes): ?>
                                                        <p>
                                                            <?php echo $language->getLine($employee->eyes->sight_right); ?> <span class="badge badge-danger"> <?php echo $language->getLine($employee->eyes->value_left); ?></span>
                                                        </p>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="profile">
                                            <h6><?php echo $language->getLine('HOBBY'); ?></h6>
                                            <p> <?php echo $language->getLine($employee->hobby); ?></p>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('SIZES'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/sizes/form', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_EDIT'); ?>
                                                </a>
                                            </h6>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('SHIRT'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $employee->size_shirt; ?></p>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('PANTS'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $employee->size_pants; ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p><?php echo $language->getLine('SHOES'); ?></p>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <p><?php echo $employee->size_shoes; ?></p>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('Contract'); ?>
                                            </h6>

                                            <?php if ($employee->contracts): ?>
                                                <?php foreach ($employee->contracts as $contract): ?>
                                                    <div class="d-flex justify-content-between align-items-center">
                                                        <?php echo $language->getLine('TYPES_OF_CONTRACTS'); ?>
                                                        <div class="btn-group btn-group-xs">
                                                            <a href="<?php $contract->files; ?>" class="btn btn-default btn-xs">
                                                                <i class="fas fa-eye"></i>
                                                            </a>
                                                        </div>
                                                    </div>

                                                    <p><?php echo $contract->number; ?></p>
                                                    <p><?php echo $language->getLine('TENURE'); ?>: <?php echo $employee->tenure ?></p>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('LEGALS'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form" href="<?php echo base_url('personal/profile/legals/add', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>
                                            <?php if ($employee->legals): ?>
                                                <?php foreach ($employee->legals as $legal): ?>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="d-flex justify-content-between align-items-center">
                                                                <?php echo $language->getLine($legal->type); ?>

                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?php echo $legal->image ?>" class="btn btn-default btn-xs">
                                                                        <i class="fas fa-eye"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/legals/edit', ['id_employee_legals' => $legal->id, 'id_employee' => $employee->id]); ?>" class="btn btn-default btn-xs" data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/legals/delete', ['id_employee_legal' => $legal->id, 'id_employee' => $employee->id]); ?>" class="btn btn-default btn-xs" data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <p class="font-weight-bold"><?php echo $legal->number; ?></p>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('Address'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/addresses/add', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>

                                            <?php if ($employee->addresses):?>
                                                <?php foreach ($employee->addresses as $address) : ?>
                                                    <div class="item">
                                                        <div class="d-flex justify-content-between align-items-center">
                                                            <strong><?php echo $address->label; ?></strong>
                                                            <div class="btn-group btn-group-xs">
                                                                <a href="<?php echo base_url('personal/profile/addresses/edit', ['id_employee' => $employee->id, 'id_employee_address' => $address->id]); ?>" class="btn btn-default btn-xs"
                                                                   data-modal="modal-form">
                                                                    <i class="fas fa-edit"></i>
                                                                </a>
                                                                <a href="<?php echo base_url('personal/profile/addresses/delete', ['id_employee' => $employee->id, 'id_employee_address' => $address->id]); ?>" class="btn btn-default btn-xs"
                                                                   data-action="delete">
                                                                    <i class="fas fa-trash"></i>
                                                                </a>
                                                            </div>
                                                        </div>
                                                        <p><?=$address->address; ?></p>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php else: ?>
                                                <div class="alert alert-warning mb-0" role="alert">
                                                    <p class="mb-0"><i class="fas fa-info-circle"></i> <?php echo $language->getLine('ALERT_DATA_EMPTY_MESSAGE_NO_BUTTON'); ?></p>
                                                </div>
                                            <?php endif; ?>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('Email'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/emails/add', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>

                                            <?php if ($employee->emails):?>
                                                <?php foreach ($employee->emails as $email) : ?>
                                                    <div class="item">
                                                        <div class="d-flex justify-content-between align-items-center">
                                                            <div>
                                                                <a href="mailto:<?php echo $email->address; ?>"> <?php echo $email->address; ?></a>
                                                                <?php if ($email->primary === 'YES'): ?>
                                                                    <span class="badge badge-info py-1">PRIMARY</span>
                                                                <?php endif; ?>
                                                            </div>
                                                            <div class="btn-group btn-group-xs">
                                                                <a href="<?php echo base_url('personal/profile/emails/add', ['id_employee' => $employee->id, 'id_employee_email' => $email->id]); ?>" class="btn btn-default btn-xs"
                                                                   data-modal="modal-form">
                                                                    <i class="fas fa-edit"></i>
                                                                </a>
                                                                <a href="<?php echo base_url('personal/profile/emails/delete', ['id_employee' => $employee->id, 'id_employee_email' => $email->id]); ?>" class="btn btn-default btn-xs"
                                                                   data-action="delete">
                                                                    <i class="fas fa-trash"></i>
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php else: ?>
                                                <div class="alert alert-warning mb-0" role="alert">
                                                    <p class="mb-0"><i class="fas fa-info-circle"></i> <?php echo $language->getLine('ALERT_DATA_EMPTY_MESSAGE_NO_BUTTON'); ?></p>
                                                </div>
                                            <?php endif; ?>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('Mobile'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/mobiles/add', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>

                                            <?php if ($employee->mobiles):?>
                                                <?php foreach ($employee->mobiles as $mobile) : ?>
                                                    <div class="item">
                                                        <div class="d-flex justify-content-between align-items-center">
                                                            <div>
                                                                <a href="tel:<?php echo $mobile->extension.$mobile->number; ?>"> <?php echo $mobile->extension.''.$mobile->number; ?></a>
                                                                <?php if ($mobile->primary === 'YES'): ?>
                                                                    <span class="badge badge-info py-1">PRIMARY</span>
                                                                <?php endif; ?>
                                                            </div>
                                                            <div class="btn-group btn-group-xs">
                                                                <a href="<?php echo base_url('personal/profile/mobiles/add', ['id_employee' => $employee->id, 'id_employee_mobile' => $mobile->id]); ?>" class="btn btn-default btn-xs"
                                                                   data-modal="modal-form">
                                                                    <i class="fas fa-edit"></i>
                                                                </a>
                                                                <a href="<?php echo base_url('personal/profile/mobiles/delete', ['id_employee' => $employee->id, 'id_employee_mobile' => $mobile->id]); ?>" class="btn btn-default btn-xs"
                                                                   data-action="delete">
                                                                    <i class="fas fa-trash"></i>
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php else: ?>
                                                <div class="alert alert-warning mb-0" role="alert">
                                                    <p class="mb-0"><i class="fas fa-info-circle"></i> <?php echo $language->getLine('ALERT_DATA_EMPTY_MESSAGE_NO_BUTTON'); ?></p>
                                                </div>
                                            <?php endif; ?>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('MEDICAL BENEFITS'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?= base_url('personal/profile/medicals/form/', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('ADD'); ?>
                                                </a>
                                            </h6>

                                            <?php if ($employee->medicals): ?>
                                                <?php foreach ($employee->medicals as $medical): ?>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="d-flex justify-content-between align-items-center">
                                                                <?php echo $medical->label; ?>
                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?=$medical->image;?>" class="btn btn-default btn-xs">
                                                                        <i class="fas fa-eye"></i>
                                                                    </a>
                                                                    <a href="<?= base_url('personal/profile/medicals/form/', ['id_employee' => $employee->id, 'id_employee_medical' => $medical->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?= base_url('personal/profile/medicals/delete/', ['id_employee' => $employee->id, 'id_employee_medical' => $medical->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <p class="font-weight-bold"><?php echo $medical->number; ?></p>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('BANKS'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?= base_url('personal/profile/banks/form', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>
                                            <?php if ($employee->banks): ?>
                                                <?php foreach ($employee->banks as $bank): ?>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="d-flex justify-content-between align-items-center">
                                                                <?php echo $bank->branch_name; ?>
                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?= base_url('personal/profile/banks/form', ['id_employee' => $employee->id, 'id_employee_bank' => $bank->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?= base_url('personal/profile/banks/delete', ['id_employee' => $employee->id, 'id_employee_bank' => $bank->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <p><?php echo $bank->branch_code; ?></p>
                                                            <p class="font-weight-bold"><?php echo $bank->account_number; ?> - <?php echo $bank->account_holder; ?></p>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>

                                    <div class="col-lg-8">
                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('FAMILIES'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/families/form', ['id_employee' => $employee->id]); ?>">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>
                                            <?php if ($employee->families): ?>
                                                <?php foreach ($employee->families as $family): ?>

                                                    <div class="item row">
                                                        <div class="col-md-12">
                                                            <div class="d-flex flex-wrap justify-content-between align-items-center">
                                                                <div class="d-flex flex-wrap">
                                                                    <p class="mb-0 font-weight-bold">
                                                                        <?php echo $family->name; ?> <span
                                                                                class="badge badge-info"><?php echo $language->getLine($family->relationship); ?></span>
                                                                    </p>
                                                                    <div class="btn-group btn-group-xs ml-3">
                                                                        <?php if ($family->gender === 'MALE'): ?>
                                                                            <button type="button"
                                                                                    class="btn btn-default btn-xs">
                                                                                <i class="fa fa-mars"></i>
                                                                            </button>
                                                                        <?php elseif ($family->gender === 'FEMALE'): ?>
                                                                            <button type="button"
                                                                                    class="btn btn-default btn-xs">
                                                                                <i class="fa fa-venus"></i>
                                                                            </button>
                                                                        <?php endif; ?>
                                                                        <?php if ($family->decease === 'YES'): ?>
                                                                            <button type="button"
                                                                                    class="btn btn-default btn-xs">
                                                                                <i class="fa fa-heart"></i>
                                                                            </button>
                                                                        <?php else: ?>
                                                                            <button type="button"
                                                                                    class="btn btn-default btn-xs">
                                                                                <i class="fa fa-heart"></i>
                                                                            </button>
                                                                        <?php endif; ?>
                                                                        <?php if ($family->amenability === 'YES'): ?>
                                                                            <button type="button"
                                                                                    class="btn btn-default btn-xs">
                                                                                <i class="fa fa-user-times"></i>
                                                                            </button>
                                                                        <?php else: ?>
                                                                            <button type="button"
                                                                                    class="btn btn-default btn-xs">
                                                                                <i class="fa fa-user-times"></i>
                                                                            </button>
                                                                        <?php endif; ?>
                                                                    </div>
                                                                </div>

                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?php echo base_url('personal/profile/families/form', ['id_employee' => $employee->id, 'id_employee_family' => $family->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/families/delete', ['id_employee' => $employee->id, 'id_employee_family' => $family->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <p class="mb-0">
                                                                <i class="fas fa-calendar"></i> <?php echo $family->birthday; ?>
                                                            </p>
                                                            <p class="mb-0">
                                                        <span>
                                                            <i class="fas fa-mobile mr-1"></i> <?php echo $language->getLine($family->mobile); ?>
                                                        </span>
                                                                <span>
                                                            <i class="fas fa-envelope mr-1"></i>
                                                            <?php echo $language->getLine($family->email); ?>
                                                        </span>
                                                            </p>
                                                            <p class="d-flex mb-3">
                                                                <i class="fas fa-map-marker-alt mr-1 mt-1"></i>
                                                                <span><?php echo $language->getLine($family->address); ?></span>
                                                            </p>
                                                        </div>
                                                    </div>

                                                <?php endforeach; ?>

                                            <?php endif; ?>
                                        </div>
                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('EDUCATIONS'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/educations/form', ['id_employee' => $employee->id]); ?>"
                                                   data-modal="modal-form">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>
                                            <?php if ($employee->educations): ?>
                                                <?php foreach ($employee->educations as $education): ?>
                                                    <div class="item row mb-3">
                                                        <div class="col-md-12">
                                                            <div class="d-flex flex-wrap justify-content-between align-items-center">
                                                                <div class="d-flex flex-wrap align-items-start">
                                                                    <div class="btn-group btn-group-xs mr-3">
                                                                        <button class="btn btn-default btn-xs">
                                                                            <i class="fa fa-graduation-cap"></i>
                                                                        </button>
                                                                        <button class="btn btn-default btn-xs">
                                                                            <i class="fa fa-certificate"></i>
                                                                        </button>
                                                                    </div>
                                                                    <p class="mb-0">
                                                                        <strong><?php echo $education->institution; ?></strong> <span class="badge badge-info"><?php echo $education->academic_year; ?></span><br>
                                                                        <?php echo $education->academic_major; ?>
                                                                    </p>
                                                                </div>
                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?php echo base_url('personal/profile/educations/form', ['id_employee' => $employee->id, 'id_employee_education' => $education->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/educations/delete', ['id_employee' => $employee->id, 'id_employee_education' => $education->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('TRAININGS'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/trainings/form', ['id_employee' => $employee->id]); ?>"
                                                   data-modal="modal-form">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>

                                            <?php if ($employee->trainings): ?>
                                                <?php foreach ($employee->trainings as $training): ?>
                                                    <div class="item row">
                                                        <div class="col-md-12">
                                                            <div class="d-flex flex-wrap justify-content-between align-items-center">
                                                                <div class="d-flex flex-wrap">
                                                                    <p class="mb-0 font-weight-bold">
                                                                        <?php echo $training->name; ?> <span
                                                                                class="badge badge-info"><?php echo $training->date; ?></span>
                                                                    </p>
                                                                    <div class="btn-group btn-group-xs ml-3">
                                                                        <button class="btn btn-default btn-xs">
                                                                            <i class="fa fa-bookmark"></i>
                                                                        </button>
                                                                    </div>
                                                                </div>

                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?=$training->image;?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-eye"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/trainings/form', ['id_employee' => $employee->id, 'id_employee_training' => $training->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/trainings/delete', ['id_employee' => $employee->id, 'id_employee_training' => $training->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <p>
                                                                <?php echo $training->organizer; ?>
                                                            </p>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('EXPERIENCES'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/experiences/form', ['id_employee' => $employee->id]); ?>"
                                                   data-modal="modal-form">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>
                                            <?php if ($employee->experiences): ?>
                                                <?php foreach ($employee->experiences as $experience): ?>
                                                    <div class="item row">
                                                        <div class="col-md-12">
                                                            <div class="d-flex flex-wrap justify-content-between align-items-center">
                                                                <div class="d-flex flex-wrap">
                                                                    <p class="mb-0 font-weight-bold">
                                                                        <?php echo $experience->company_name; ?> <span
                                                                                class="badge badge-info"><?php echo $experience->tenure; ?></span>
                                                                    </p>
                                                                </div>

                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?php echo base_url('personal/profile/experiences/form', ['id_employee' => $employee->id, 'id_employee_experience' => $employee->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/experiences/delete', ['id_employee' => $employee->id, 'id_employee_experience' => $employee->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <p class="mb-0">
                                                                <?php if ($experience->company_department): ?>
                                                                    <?php echo $experience->company_department; ?>
                                                                    &mdash;
                                                                    <?php echo $experience->company_department_position; ?>
                                                                <?php else: ?>
                                                                    <?php echo $experience->company_department_position; ?>
                                                                <?php endif; ?>
                                                            </p>
                                                            <p><?php echo date('d, M Y', strtotime($experience->date_start)).' - '.date('d, M Y', strtotime($experience->date_end)); ?></p>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>

                                        </div>

                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('LANGUAGES'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/languages/form', ['id_employee' => $employee->id]); ?>"
                                                   data-modal="modal-form">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>
                                            <?php if ($employee->languages): ?>
                                                <?php foreach ($employee->languages as $lang): ?>
                                                    <div class="item row mb-3">
                                                        <div class="col-md-12">
                                                            <div class="d-flex flex-wrap justify-content-between align-items-center">
                                                                <div class="d-flex flex-wrap">
                                                                    <p class="mb-0 font-weight-bold">
                                                                        <?php echo $lang->name; ?>
                                                                    </p>
                                                                </div>

                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?php echo base_url('personal/profile/languages/form', ['id_employee' => $employee->id, 'id_employee_language' => $lang->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/languages/delete', ['id_employee' => $employee->id, 'id_employee_language' => $lang->id]); ?>" class="btn btn-default btn-xs"
                                                                       data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <div class="d-flex flex-wrap align-items-center">
                                                                <div class="btn-group btn-group-xs mr-3">
                                                                    <button class="btn btn-default btn-xs">
                                                                            <?php echo $language->getLine('READ'); ?>
                                                                    </button>
                                                                    <button class="btn btn-primary btn-xs">
                                                                        <?php echo $language->getLine($lang->grade_read); ?>
                                                                    </button>
                                                                </div>
                                                                <div class="btn-group btn-group-xs mr-3">
                                                                    <button class="btn btn-default btn-xs">
                                                                            <?php echo $language->getLine('WRITE'); ?>
                                                                    </button>
                                                                    <button class="btn btn-primary btn-xs">
                                                                        <?php echo $language->getLine($lang->grade_write); ?>
                                                                    </button>
                                                                </div>
                                                                <div class="btn-group btn-group-xs mr-3">
                                                                    <button class="btn btn-default btn-xs">
                                                                            <?php echo $language->getLine('SPOKE'); ?>
                                                                    </button>
                                                                    <button class="btn btn-primary btn-xs">
                                                                        <?php echo $language->getLine($lang->grade_spoke); ?>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>

                                        </div>
                                        <div class="profile">
                                            <h6>
                                                <?php echo $language->getLine('SKILLS'); ?>
                                                <a class="btn btn-primary btn-sm" data-modal="modal-form"
                                                   href="<?php echo base_url('personal/profile/skills/form', ['id_employee' => $employee->id]); ?>"
                                                   data-modal="modal-form">
                                                    <?php echo $language->getLine('BTN_ADD'); ?>
                                                </a>
                                            </h6>
                                            <?php if ($employee->skills): ?>
                                                <?php foreach ($employee->skills as $skill): ?>
                                                    <div class="item row mb-3">
                                                        <div class="col-md-12">
                                                            <div class="d-flex flex-wrap justify-content-between align-items-center">
                                                                <div class="d-flex flex-wrap">
                                                                    <p class="mb-0 font-weight-bold">
                                                                        <?php echo $skill->name; ?>
                                                                        <span class="badge badge-info">
                                                                            <?php echo $language->getLine($skill->grade); ?>
                                                                        </span>
                                                                    </p>
                                                                </div>

                                                                <div class="btn-group btn-group-xs">
                                                                    <a href="<?php echo base_url('personal/profile/skills/form', ['id_employee' => $employee->id, 'id_employee_skill' => $skill->id]); ?>" class="btn btn-default btn-xs" data-modal="modal-form">
                                                                        <i class="fas fa-edit"></i>
                                                                    </a>
                                                                    <a href="<?php echo base_url('personal/profile/skills/delete', ['id_employee' => $employee->id, 'id_employee_skill' => $skill->id]); ?>" class="btn btn-default btn-xs"  data-action="delete">
                                                                        <i class="fas fa-trash"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>
            </div>
        </div>
    </div>
</div>