<div class="page-documentations">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <?=view('partials/sidebar', [], true)?>
            </div>
            <div class="col-md">
                <div class="documentations-title">
                    <div class="inner">
                        <h1 data-toc-skip>
	                        Personal Module
                        </h1>
                        <div class="meta">
                            <p>Last Update <?=date('r', $page->file->getMTime())?></p>
                        </div>
                    </div>
                </div>

                <div class="documentations-content" id="documentations-content">
                    Pada modul personal terdapat beberapa sub-module yaitu :
                    <a href="<?php echo base_url('personal/agenda');?>" class="text-primary"><strong>Agenda</strong></a>,
                    <a href="<?php echo base_url('personal/notes');?>" class="text-primary"><strong>Notes</strong></a>,
                    <a href="<?php echo base_url('personal/tasks');?>" class="text-primary"><strong>Tasks</strong></a>,
                    <a href="<?php echo base_url('personal/profile/career');?>" class="text-primary"><strong>Career</strong></a>,
                    <a href="<?php echo base_url('personal/profile/schedules');?>" class="text-primary"><strong>Schedules</strong></a>,
                    <a href="<?php echo base_url('personal/profile/attendances');?>" class="text-primary"><strong>Attendance</strong></a>,
                    <a href="<?php echo base_url('personal/leaves');?>" class="text-primary"><strong>Leaves</strong></a>,
                    <a href="<?php echo base_url('personal/payroll');?>" class="text-primary"><strong>Payroll</strong></a>,
                    <a href="<?php echo base_url('personal/evaluations');?>" class="text-primary"><strong>Evaluation</strong></a>,
                    <a href="<?php echo base_url('personal/reprimands');?>" class="text-primary"><strong>Reprimands</strong></a>,
                    <a href="<?php echo base_url('personal/inventories');?>" class="text-primary"><strong>Inventories</strong></a>,
                    <a href="<?php echo base_url('personal/leases');?>" class="text-primary"><strong>Leases</strong></a>,
                    <a href="<?php echo base_url('personal/apprasial');?>" class="text-primary"><strong>Apprasial</strong></a>,
                    <a href="<?php echo base_url('personal/learning');?>" class="text-primary"><strong>Learning</strong></a> dan
                    <a href="<?php echo base_url('personal/trainings');?>" class="text-primary"><strong>Trainings</strong></a>
                    <br> berikut ini merupakan tutorial mengelola data pada modul personal </p>


                    <h3><a href="<?php echo base_url('personal/schedule/agenda');?>" class="text-primary"><strong>Agenda Submodule</strong></a></h3>
                    <p>submodul ini merupakan informasi kegiatan berdasarkan jadwal harian, mingguan dan bulanan.
                        klik tombol <a href="<?php echo base_url('personal/agenda');?>" class="text-primary"><strong>Agenda</strong></a> pada menu sidebar</p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/agenda/1.0.png')?>" class="img-browser">

                    untuk melihat jadwal bulanan tekan tombol <strong>Month</strong>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/agenda/1.2.png')?>" class="img-browser">

                    untuk melihat jadwal mingguan tekan tombol <strong>Week</strong>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/agenda/1.1.png')?>" class="img-browser">

                    untuk melihat jadwal harian tekan tombol <strong>Days</strong>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/agenda/1.3.png')?>" class="img-browser">

                    dan tombol <strong>List</strong> untuk melihat jadwal secara detail

                    <img src="<?=public_url('modules/documentations/assets/img/personal/agenda/1.4.png')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/notes');?>" class="text-primary"><strong>Notes Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Notes</strong></a>,
                        Klik tombol <strong>Add New Notes</strong></p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/notes/1.0.0.png')?>" class="img-browser">

                    beri title pada label Notes tersebut kemudian tekan <strong>Save</strong>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/notes/1.1.png')?>" class="img-browser">

                     lalu tekan tanda <strong>(+)</strong> untuk menambahkan notes baru pada label tersebut

                    <img src="<?=public_url('modules/documentations/assets/img/personal/notes/1.2.png')?>" class="img-browser">

                    isi form (beri judul) kemudian klik <strong>Save</strong>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/notes/1.3.png')?>" class="img-browser">

                    klik pada judul untuk menambahkan atau mengubah isi pada notes tersebut

                    <img src="<?=public_url('modules/documentations/assets/img/personal/notes/1.4.png')?>" class="img-browser">


                    <h3><a href="<?php echo base_url('personal/tasks');?>" class="text-primary"><strong>Tasks Submodule</strong></a></h3>
                    <p>Submodule Task merupakan data yang di tampilkan dari Boards, klik menu <strong>Create a Team</strong> </p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/tasks/1.0.0.png')?>" class="img-browser">

                    <p>Isi form Add-Team dan pilih warna label nya lalu klik <strong>Save</strong> </p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/tasks/1.0.1.png')?>" class="img-browser">

                    <p> Pilih Personal / Company Board kemudian klik <strong>create a board</strong> </p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/tasks/1.0.2.png')?>" class="img-browser">

                    <p> Isi kolom Name dan Description kemudian klik <strong>Save</strong> </p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/tasks/1.0.3.png')?>" class="img-browser">


                    <h3><a href="<?php echo base_url('personal/profile/career');?>" class="text-primary"><strong>Career Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Career</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/profile/schedules');?>" class="text-primary"><strong>Schedule Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Schedule</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/profile/attendances');?>" class="text-primary"><strong>Attendance Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Attendance</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/attendance/1.0.png')?>" class="img-browser">


                    <h3><a href="<?php echo base_url('personal/leaves');?>" class="text-primary"><strong>Leaves Submodule</strong></a></h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Leaves</strong></a> ke dalam aplikasi,
                    Klik tombol <strong>Add Request</strong> </p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/leaves/1.0.png')?>" class="img-browser">

                    Isi Form nya, lalu klik tombol <strong>Request</strong>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/leaves/1.1.png')?>" class="img-browser">

                    kemudian muncul notif <strong> Well Done </strong> jika data berhasil disimpan,
                    Pada sebelah tanggal terdapat tombol (icon pen) untuk mengupdate data & (icon trash) untuk menghapus data .

                    <img src="<?=public_url('modules/documentations/assets/img/personal/leaves/1.2.png')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/payroll');?>" class="text-primary"><strong>Payroll Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Payroll</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/evaluations');?>" class="text-primary"><strong>Evaluation Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Evaluation</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/reprimands');?>" class="text-primary"><strong>reprimands Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>reprimands</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/inventories');?>" class="text-primary"><strong>Inventories Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Inventories</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/leases');?>" class="text-primary"><strong>Leases Submodule</strong></a> </h3>
                    <p>Berikut ini merupakan cara menambahkan data pada sub module <a href="#" class="text-primary"><strong>Leases</strong></a> ke dalam aplikasi, </p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">

                    <h3><a href="<?php echo base_url('personal/apprasial');?>" class="text-primary"><strong>Apprasial Submodule</strong></a></h3>
                    <p></p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/appraisal/1.0.png')?>" class="img-browser">


                    <h3><a href="<?php echo base_url('personal/learning');?>" class="text-primary"><strong>Learning Submodule</strong></a></h3>
                    <p></p>

                    <img src="<?=public_url('modules/documentations/assets/img/personal/learning-certification/1.0.png')?>" class="img-browser">

                    <img src="<?=public_url('modules/documentations/assets/img/personal/learning-certification/1.1.png')?>" class="img-browser">

                    <img src="<?=public_url('modules/documentations/assets/img/personal/learning-certification/1.2.png')?>" class="img-browser">

                    <img src="<?=public_url('modules/documentations/assets/img/personal/learning-certification/1.3.png')?>" class="img-browser">



                    <h3><a href="<?php echo base_url('personal/trainings');?>" class="text-primary"><strong>Trainings Submodule</strong></a></h3>
                    <p></p>

                    <img src="<?=public_url('modules/documentations/assets/img/no-data.jpg')?>" class="img-browser">


                </div>
            </div>
            <div class="col-md-3">
                <nav id="toc">
                    <ul class="toc-nav">
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>