<div class="documentations-sidebar">
    <ul>
        <li class="title-menu">Modules</li>
        <li>
            <a href="<?=base_url('documentations/personal-module')?>"> <i class="fas fa-user"></i> Personal Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/company-module')?>"> <i class="fas fa-briefcase"></i> Company Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/human-resource-module')?>"> <i class="fas fa-users"></i> Human Resource Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/building-management-module')?>"> <i class="fas fa-building"></i> Building Management Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/finance-module')?>"> <i class="fas fa-money-bill"></i> Finance Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/goods-module')?>"> <i class="fas fa-boxes"></i> Goods Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/office-module')?>"> <i class="fas fa-paperclip"></i> Office Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/training-module')?>"> <i class="fas fa-chalkboard-teacher"></i> Trainings Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/customers-module')?>"> <i class="fas fa-user-friends"></i> Customers Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/assets-management-module')?>"> <i class="fas fa-cubes"></i> Assets Module</a>
        </li>
        <li>
            <a href="<?=base_url('documentations/shuttle-module')?>"> <i class="fas fa-car"></i> Shuttle Module</a>
        </li>
    </ul>
</div>