<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Enable</button>
                            <button class="btn btn-default"><i class="fa fa-times-circle text-danger"></i> Disable</button>
                            <button class="btn btn-default"><i class="fa fa-refresh"></i> Refresh Cache</button>
                            <button class="btn btn-default"><i class="fa fa-times"></i> Uninstall</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
        	<div class="card-header">
        		<form class="form-inline">
    				<div class="form-group">
        				<div class="input-group">
                            <input class="form-control" placeholder="Search for..." type="text">
                            <span class="input-group-btn">
                              <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
        			</div>
        			<div class="form-group ml-3">
        				<button class="btn btn-default" type="button">Clear</button>
        			</div>
        			<div class="form-group ml-3">
        				<select class="form-control custom-select">
        					<option>Name Ascending</option>
        				</select>
        			</div>
        			<div class="form-group ml-3">
        				<select class="form-control custom-select">
        					<option>20</option>
        				</select>
        			</div>
        		</form>
        	</div>
            <div class="card-body">
                <div>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th width="1%">
                                    <div class="form-check">
                                        <label class="custom-control custom-checkbox">
                                            <input id="checkbox-1" class="custom-control-input" type="checkbox">
                                            <span class="custom-control-indicator"></span>
                                        </label>
                                    </div>
                                </th>
                                <th width="5%">Status</th>
                                <th>Name</th>
                                <th>Location</th>
                                <th>Type</th>
                                <th>Version</th>
                                <th>Date</th>
                                <th>Author</th>
                                <th>Folder</th>
                                <th>Package ID</th>
                                <th>ID</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>
                                    <div class="form-check">
                                        <label class="custom-control custom-checkbox">
                                            <input class="custom-control-input" type="checkbox">
                                            <span class="custom-control-indicator"></span>
                                        </label>
                                    </div>
                                </td>
                                <td><button class="btn btn-xs btn-default"><i class="fa fa-check text-success"></i></button></td>
                                <td>Administrator Menu</td>
                                <td>Administrator</td>
                                <td>Module</td>
                                <td>3.0.0</td>
                                <td>March 2016</td>
                                <td>John</td>
                                <td>N/A</td>
                                <td></td>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-check">
                                        <label class="custom-control custom-checkbox">
                                            <input class="custom-control-input" type="checkbox">
                                            <span class="custom-control-indicator"></span>
                                        </label>
                                    </div>
                                </td>
                                <td><button class="btn btn-xs btn-default"><i class="fa fa-times text-danger"></i></button></td>
                                <td>Administrator Menu</td>
                                <td>Administrator</td>
                                <td>Module</td>
                                <td>3.0.0</td>
                                <td>March 2016</td>
                                <td>John</td>
                                <td>N/A</td>
                                <td></td>
                                <td>35</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Enable</button>
                            <button class="btn btn-default"><i class="fa fa-times-circle text-danger"></i> Disable</button>
                            <button class="btn btn-default"><i class="fa fa-refresh"></i> Refresh Cache</button>
                            <button class="btn btn-default"><i class="fa fa-times"></i> Uninstall</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>