<div class="page-administrator">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="card">
                    <div class="card-header d-flex align-items-center justify-content-between p-0 pr-3">
                        <div class="nav-pages">
                            <ul class="nav">
                                <!-- <li class="nav-item">
                                    <a class="nav-link" href="<?=base_url('system/users/profiles')?>"><?php echo $language->getLine('USERS'); ?></a>
                                </li> -->
                                <li class="nav-item">
                                    <a class="nav-link active" href="<?=base_url('system/users/roles')?>"><?php echo $language->getLine('ROLES'); ?></a>
                                </li>
                            </ul>
                        </div>
                        <?php if(services('user')->hasWriteAccess()): ?>
                            <a href="<?=base_url('system/users/roles/form'); ?>" class="btn btn-primary btn-md">
                                <?=language('BTN_ADD_NEW')?>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>

                <?php if($roles):?>
                    <div class="card">
                        <div class="card-body with-table">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>
                                                <?php echo $language->getLine('CODE'); ?>
                                            </th>
                                            <th>
                                                <?php echo $language->getLine('LABEL'); ?>
                                            </th>
                                            <th>
                                                <?php echo $language->getLine('DESCRIPTION'); ?>
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($roles as $role):?>
                                            <tr>
                                                <td>
                                                    <a href="<?=base_url('system/users/roles/detail/'.$role->id);?>" class="d-flex align-items-center">
                                                        <span class="btn btn-default btn-xs text-uppercase"><?=$role->code;?></span>
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="<?=base_url('system/users/roles/detail/'.$role->id);?>" class="d-flex align-items-center">
                                                        <?=$role->label?>
                                                    </a>
                                                </td>
                                                <td>
                                                    <?=$role->description;?>
                                                </td>
                                                <td>
                                                    <div class="btn btn-group btn-group-sm">
                                                        <a href="<?=base_url('system/users/roles/detail/'.$role->id);?>" class="btn btn-default btn-sm">
                                                            <i class="fas fa-eye"></i>
                                                        </a>
                                                        <?php if(services('user')->hasWriteAccess()): ?>
                                                            <a class="btn btn-default btn-sm" href="<?=base_url('system/users/roles/edit/'.$role->id);?>"> 
                                                                <i class="fas fa-edit"></i> 
                                                            </a>
                                                            <a class="btn btn-default btn-sm" href="<?=base_url('system/users/roles/delete/'.$role->id);?>"> 
                                                                <i class="fa fa-trash"></i> 
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php endforeach;?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <!-- <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('administrator/roles', ['page' => input()->get('page') - 1]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('BTN_PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('administrator/roles', ['page' => $page + 1]); ?>" class="btn btn-default <?=$page >= $roles->info->total->pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('BTN_NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $roles->info->total->pages; ++$i):?>
                                                    <option value="<?=$i; ?>"><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary"><?php echo $language->getLine('BTN_GO'); ?></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <p class="mb-0 text-lowercase text-muted"><?php echo $language->getLine('SHOW'); ?> <span><?=$roles->info->numbering->start; ?></span> <?php echo $language->getLine('TO'); ?> <span><?=$roles->info->numbering->end; ?></span> <?php echo $language->getLine('FROM'); ?> <span><?=$roles->info->total->rows; ?></span></p>
                        </div>
                    </div> -->
                <?php else:?>
                    <div class="row justify-content-center">
                        <div class="col-lg-12 text-center p-3">
                            <img src="{{storage_url('images/default/no-image.jpg')}}" class="img-fluid">
                            <h3 class="mt-3"><?php echo $language->getLine('ALERT_DATA_EMPTY_HEADING'); ?></h3>
                            <h6 class="text-danger mb-4">
                                <?php echo $language->getLine('ALERT_DATA_EMPTY_MESSAGE'); ?>
                            </h6>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </div>
        <!-- Pagination -->
    </div>
</div>