<div class="page-administrator">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="card">
                    <div class="card-header d-flex align-items-center justify-content-between p-0 pr-3">
                        <div class="nav-pages">
                            <ul class="nav">
                                <!-- <li class="nav-item">
                                    <a class="nav-link" href="<?=base_url('administrator')?>"><?php echo $language->getLine('USERS'); ?></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?=base_url('administrator/modules/roles')?>"><?php echo $language->getLine('ROLES'); ?></a>
                                </li> -->
                                <li class="nav-item">
                                    <a class="nav-link active" href="<?=base_url('/system/modules')?>"><?php echo $language->getLine('MODULES'); ?></a>
                                </li>
                            </ul>
                        </div>
                        <?php if(services('user')->hasWriteAccess()): ?>
                            <a href="<?=base_url('modules/form'); ?>" class="btn btn-primary btn-md">
                                <?=language('BTN_ADD_NEW')?>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>

                <?php if($modules):?>
                    <div class="card">
                        <div class="card-body with-table">
                            <div class="table-responsive">
                                <table class="table table-striped valign-middle">
                                    <thead>
                                    <tr>
                                        <th><?=language('NAMESPACE')?></th>
                                        <th><?=language('TYPE')?></th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach($modules as $module): ?>
                                        <tr>
                                            <td>
                                                <a href="<?=base_url('system/modules/detail/' . $module->id); ?>">
                                                    <?php echo str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;', $module->record_depth); ?>
                                                    <?php echo ($module->record_depth == 0 ? '' : '&#8627;'); ?>

                                                    <?=$module->namespace?>
                                                </a>
                                            </td>
                                            <td>
                                                <span class="text-uppercase badge badge-info"><?=$module->type?></span>
                                            </td>
                                            <td>
                                                <?php if(services('user')->hasWriteAccess()): ?>
                                                    <div class="btn-group btn-group-sm">
                                                        <a class="btn btn-default btn-sm" href="<?=base_url('system/modules/form/' . $module->id); ?>">
                                                            <i class="fas fa-edit"></i>
                                                        </a>
                                                        <a class="btn btn-default btn-sm" href="<?=base_url('system/modules/delete/' . $module->id); ?>" data-action="delete">
                                                            <i class="fa fa-trash"></i>
                                                        </a>
                                                    </div>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach;?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <!-- <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('administrator/modules', ['page' => input()->get('page') - 1]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('BTN_PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('administrator/modules', ['page' => $page + 1]); ?>" class="btn btn-default <?=$page >= $modules->info->total->pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('BTN_NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $modules->info->total->pages; ++$i):?>
                                                    <option value="<?=$i; ?>"><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary"><?php echo $language->getLine('BTN_GO'); ?></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <p class="mb-0 text-lowercase text-muted"><?php echo $language->getLine('SHOW'); ?> <span><?=$modules->info->numbering->start; ?></span> <?php echo $language->getLine('TO'); ?> <span><?=$modules->info->numbering->end; ?></span> <?php echo $language->getLine('FROM'); ?> <span><?=$modules->info->total->rows; ?></span></p>
                        </div>
                    </div> -->

                <?php else:?>
                    <div class="row justify-content-center">
                        <div class="col-lg-12 text-center p-3">
                            <img src="{{storage_url('images/default/no-departments-image.png')}}" class="img-fluid">
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>