<div class="page-administrator">
    <div class="container-fluid">
        <form method="post" enctype="multipart/form-data" action="<?=current_url();?>">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10">
                    <div class="card">
                        <div class="card-header d-flex flex-wrap align-items-center justify-content-between p-0">
                            <div class="nav-pages">    
                                <ul class="nav" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="tab" href="#user-account" role="tab" aria-controls="user-account" aria-selected="true">
	                                        <?=language('ACCOUNT')?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-options px-3">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="tab-content p-0 border-0 mb-0">
                                <div class="tab-pane active" id="user-account" role="tabpanel" aria-labelledby="user-account">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label><?php echo $language->getLine('USERNAME'); ?></label>
                                                <input class="form-control" type="text" name="username" value="<?=$post->username;?>" disabled>
                                                <div class="valid-feedback">
                                                    <i class="fas fa-check"></i> <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <i class="fas fa-info-circle"></i> <?php echo $language->getLine('EXAMPLE'); ?>: youremail@gmail.com
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label><?php echo $language->getLine('EMAIL'); ?></label>
                                                <input class="form-control" type="email" name="email" value="<?=$post->email;?>">
                                                <div class="valid-feedback">
                                                    <i class="fas fa-check"></i> <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <i class="fas fa-info-circle"></i> <?php echo $language->getLine('EXAMPLE'); ?>: youremail@gmail.com
                                                </div>
                                            </div>
                                        </div>
            
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label><?php echo $language->getLine('CHANGE_PASSWORD'); ?></label>
                                                <input class="form-control" type="password" name="password" value="">
                                                <div class="valid-feedback">
                                                    <i class="fas fa-check"></i> <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <i class="fas fa-info-circle"></i> <?php echo $language->getLine('EXAMPLE'); ?>: P@s5W0rD!
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label><?php echo $language->getLine('CHANGE_CONFIRM_PASSWORD'); ?> </label>
                                                <input class="form-control" type="password" name="password_confirm" value="">
                                                <div class="valid-feedback">
                                                    <i class="fas fa-check"></i> <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <i class="fas fa-info-circle"></i> <?php echo $language->getLine('EXAMPLE'); ?>: P@s5W0rD!
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>