<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Table Tools</div>
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <button class="btn btn-success"><i class="fa fa-list"></i></button>
                            <button class="btn btn-primary"><i class="fa fa-pencil"></i></button>
                            <button class="btn btn-warning"><i class="fa fa-check"></i></button>
                            <button class="btn btn-default"><i class="fa fa-ban"></i></button>
                            <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                            <button class="btn btn-info"><i class="fa fa-archive"></i></button>
                        </div>
                        <div class="col-sm-6 text-right">
                            <select class="custom-select" title="Column">
                                <option>Column1</option>
                                <option>Column2</option>
                            </select>
                            <a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <select class="form-control custom-select" title="Field">
                                        <option>Field1</option>
                                        <option>Field2</option>
                                    </select>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <select class="custom-select" title="Date">
                                <option>1</option>
                                <option>2</option>
                            </select>
                            <select class="custom-select" title="Month">
                                <option>January</option>
                                <option>February</option>
                            </select>
                            <select class="custom-select" title="Year">
                                <option>2016</option>
                                <option>2017</option>
                            </select>
                            <select class="custom-select" title="Type">
                                <option>Type1</option>
                                <option>Type2</option>
                            </select>
                        </div>
                        <div class="col-md-3 text-right">
                            <select class="custom-select" title="Status">
                                <option>Public</option>
                                <option>Draft</option>
                            </select>
                            <select class="custom-select" data-style="btn-default">
                                <option>20</option>
                                <option>40</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-0">
                        <div class="col-md-4">
                            <button class="btn btn-warning">Reset <i class="fa fa-repeat"></i></button>
                            <button class="btn btn-primary">Submit <i class="fa fa-search"></i></button>
                        </div>
                        <div class="col-md-8 pagination-page text-right">
                            <div class="input-group">
                                <span class="input-group-addon"><strong>1-20 of 200</strong> - Page 1 of 10</span>
                                <input type="text" class="form-control" placeholder="Go to page...">
                                <ul class="pagination">
                                    <li class="page-item disabled">
                                        <a href="#" class="page-link disabled">
                                            <span aria-hidden="true">
                                            «
                                            </span>
                                        </a>
                                    </li>
                                    <li class="page-item active">
                                        <a href="ui/?page=1" class="page-link">
                                            1
                                            <span class="sr-only">
                                            (current)
                                            </span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=2" class="page-link">
                                            2
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=3" class="page-link">
                                            3
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=4" class="page-link">
                                            4
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=5" class="page-link">
                                            5
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=2" class="page-link">
                                            <span aria-hidden="true">
                                            »
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body with-table">
                <div class="table-responsive">
                    <table class="table table-bordered table-responsive">
                        <thead>
                            <tr>
                                <th width="1%">
                                    <div class="form-check">
                                        <label class="custom-control custom-checkbox">
                                            <input id="checkbox-1" class="custom-control-input" type="checkbox">
                                            <span class="custom-control-indicator"></span>
                                        </label>
                                    </div>
                                </th>
                                <th width="4%">#</th>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Progress</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>
                                    <div class="form-check">
                                        <label class="custom-control custom-checkbox">
                                            <input class="custom-control-input" type="checkbox">
                                            <span class="custom-control-indicator"></span>
                                        </label>
                                    </div>
                                </td>
                                <td>1</td>
                                <td>Arlind</td>
                                <td>Nushi</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="javascript:void(0);" class="btn btn-default btn-sm"><i class="fa fa-edit"></i></a>
                                    <a href="javascript:void(0);" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <div class="form-check">
                                        <label class="custom-control custom-checkbox">
                                            <input class="custom-control-input" type="checkbox">
                                            <span class="custom-control-indicator"></span>
                                        </label>
                                    </div>
                                </td>
                                <td>2</td>
                                <td>Art</td>
                                <td>Ramadani</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="92" aria-valuemin="0" aria-valuemax="100" style="width: 92%">
                                            <span class="sr-only">92% Complete</span>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="javascript:void(0);" class="btn btn-default btn-sm"><i class="fa fa-edit"></i></a>
                                    <a href="javascript:void(0);" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <div class="form-check">
                                        <label class="custom-control custom-checkbox">
                                            <input class="custom-control-input" type="checkbox">
                                            <span class="custom-control-indicator"></span>
                                        </label>
                                    </div>
                                </td>
                                <td>3</td>
                                <td>Filan</td>
                                <td>Fisteku</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                                            <span class="sr-only">70% Complete</span>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="javascript:void(0);" class="btn btn-default btn-sm"><i class="fa fa-edit"></i></a>
                                    <a href="javascript:void(0);" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-4"></div>
                        <div class="col-md-8 pagination-page text-right">
                            <div class="input-group">
                                <span class="input-group-addon"><strong>1-20 of 200</strong> - Page 1 of 10</span>
                                <input type="text" class="form-control" placeholder="Go to page...">
                                <ul class="pagination">
                                    <li class="page-item disabled">
                                        <a href="#" class="page-link disabled">
                                            <span aria-hidden="true">
                                            «
                                            </span>
                                        </a>
                                    </li>
                                    <li class="page-item active">
                                        <a href="ui/?page=1" class="page-link">
                                            1
                                            <span class="sr-only">
                                            (current)
                                            </span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=2" class="page-link">
                                            2
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=3" class="page-link">
                                            3
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=4" class="page-link">
                                            4
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=5" class="page-link">
                                            5
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="ui/?page=2" class="page-link">
                                            <span aria-hidden="true">
                                            »
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>