<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <?php if($company):?>
                    <div class="row justify-content-center pb-5 pt-3">
                        <div class="col-lg-12 d-flex justify-content-center">
                            <div class="media align-items-center mb-4">
                                <div class="avatar">
                                    <?php if(is_object($company->metadata)):?>
                                        <img src="<?=$company->metadata->logo;?>" class="mr-3 rounded-circle" width="72" height="72" alt="<?=$company->name;?>">
                                    <?php endif ;?>
                                </div>
                                <div class="media-body d-flex align-items-center justify-content-between">
                                    <div>
                                        <h1>
                                            <a href="<?=base_url('administrator/companies/detail/' . $company->id); ?>"><?=$company->name?></a>
                                        </h1>
                                        <h6>
                                        </h6>
                                        <button class="btn btn-primary btn-xs btn-icon">
                                            <i class="fas fa-user-lock"></i> <?=$company->code?>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif;?>

                <div class="tab-content border-0 p-0">
                    <div class="tab-pane fade show active" id="authorities" role="tabpanel">
                        <form action="<?=current_url();?>" method="post">
                            <input type="hidden" name="id_company" value="<?=$company->id;?>">
                            <div class="card">
                                <h5 class="card-header d-flex align-items-center justify-content-between">
                                    <?php echo $language->getLine('MANAGE_USER_COMPANY'); ?>
                                    <?php if(hasWriteAccess()):?>
                                        <button class="btn btn-primary" type="submit"><?php echo $language->getLine('BTN_SAVE'); ?></button>
                                    <?php endif;?>
                                </h5>
                                <div class="card-body">
                                    <select class="multiselect-search" name="id_sys_user[]" multiple="multiple">
                                        <?php if($users):?>
                                            <?php foreach ($users as $user):?>
                                                <option value="<?=$user->id;?>"
                                                    <?php if($company->users):?>
                                                        <?php foreach ($company->users as $companyUser):?>
                                                            <?php if($companyUser->id_sys_user === $user->id):?>
                                                                selected
                                                            <?php endif;?>
                                                        <?php endforeach;?>
                                                    <?php endif;?>
                                                ><?=$user->username .' - '.$user->email?></option>
                                            <?php endforeach;?>
                                        <?php endif;?>
                                    </select>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>