<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-lg-4 col-md-6">
			<div class="card">
				<div class="card-body">
					<div class="logo text-center">
						<a href="javascript:void(0);">
							<img src="assets/img/logo/color.png">
						</a>
					</div>
					<form>
						<div class="form-group">
							<label for="username">Enter your email</label>
							<input type="email" class="form-control" id="username" placeholder="email@example.com">
						</div>
                        <div class="form-group text-right">
                            <button class="btn btn-primary" type="submit">Reset Password</button>
                        </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>