<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form  method="POST" action="<?php echo current_url(); ?>" class="needs-validation" novalidate>
                    <div class="card">
                        <h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->header; ?>
                            <div class="card-options">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url();?>">
                            <div class="form-group">
                                <label for="address_label"><?php echo $language->getLine('ADDRESS_LABEL'); ?></label>
                                <input type="hidden" name="id" value="<?=$post->id;?>">
                                <input id="address_label" type="text" class="form-control" name="label" value="<?=$post->label;?>" placeholder="Address Label" required>
                            </div>
                            <div class="form-group">
                                <label for="address_description"><?php echo $language->getLine('ADDRESS_DESCRIPTION'); ?></label>
                                <textarea id="address_description" class="form-control" placeholder="Address" name="address"  required><?=$post->address;?></textarea>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>