<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form  method="post" action="<?php echo current_url(); ?>" class="needs-validation" novalidate>
                    <div class="card">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->header; ?>
                            <div class="card-options">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </div>
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
                            <input type="hidden" name="id" value="<?php echo $post->id; ?>">
                            <div class="row">
                                <div class="col-md">
                                    <div class="form-group">
                                        <label class="d-block"><?php echo $language->getLine('GENDER'); ?></label>
                                        <div class="form-check-inline">
                                            <div class="radio">
                                                <input type="radio" name="gender" id="radio-male" value="MALE" <?php echo($post->gender === 'MALE' ? 'checked' : ''); ?> required>
                                                <label for="radio-male"> <?php echo $language->getLine('MALE'); ?> </label>
                                                <div class="valid-feedback">
                                                    <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-check-inline">
                                            <div class="radio">
                                                <input type="radio" name="gender"  id="radio-female" value="FEMALE" <?php echo($post->gender === 'FEMALE' ? 'checked' : ''); ?> required>
                                                <label for="radio-female"> <?php echo $language->getLine('FEMALE'); ?> </label>
                                                <div class="valid-feedback">
                                                    <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md">
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label><?php echo $language->getLine('BLOOD_TYPE'); ?></label>
                                                <select class="form-control custom-select" name="blood" required>
                                                    <option>A</option>
                                                    <option>B</option>
                                                    <option>AB</option>
                                                    <option>O</option>
                                                </select>
                                                <div class="valid-feedback">
                                                    <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label>Blood Rhesus</label>
                                                <select class="form-control custom-select" name="rhesus" required>
                                                    <?php $rhesus = ['YES' => 'Positive', "NO" => 'Negative' ]?>
                                                    <?php foreach ($rhesus as $value => $label): ?>
                                                        <option value ="<?=$value;?>"
                                                            <?=($post->rhesus == $value ? 'selected' : "");?>>
                                                            <?=$label;?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                                <div class="valid-feedback">
                                                    <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                                </div>
                                                <div class="invalid-feedback">
                                                    <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <div class="form-group">
                                        <label><?php echo $language->getLine('BIRTHPLACE'); ?></label>
                                        <input type="text" class="form-control" name="birthplace" value="<?php echo $post->birthplace; ?>" required>
                                        <div class="valid-feedback">
                                            <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                        </div>
                                        <div class="invalid-feedback">
                                            <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <label><?php echo $language->getLine('BIRTHDAY'); ?></label>
                                    <div class="form-row">
                                        <div class="form-group col">
                                            <select name="birthday[date]" class="form-control custom-select" required>
                                                <?php foreach($options->dates as $value => $label): ?>
                                                    <option value="<?php echo $value; ?>" <?php echo($value == format_date($post->birthday, '%d') ? 'selected' : ''); ?>>
                                                        <?php echo $label; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                            <div class="valid-feedback">
                                                <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                            </div>
                                            <div class="invalid-feedback">
                                                <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                            </div>
                                        </div>
                                        <div class="form-group col">
                                            <select name="birthday[month]" class="form-control custom-select" required>
                                                <?php foreach($options->months as $value => $label): ?>
                                                    <option value="<?php echo $value; ?>" <?php echo($value == format_date($post->birthday, '%m') ? 'selected' : ''); ?>>
                                                        <?php echo $label; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                            <div class="valid-feedback">
                                                <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                            </div>
                                            <div class="invalid-feedback">
                                                <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                            </div>
                                        </div>
                                        <div class="form-group col">
                                            <select name="birthday[year]" class="form-control custom-select" required>
                                                <?php foreach($options->years as $value => $label): ?>
                                                    <option value="<?php echo $value; ?>" <?php echo($value == format_date($post->birthday, '%Y') ? 'selected' : ''); ?>>
                                                        <?php echo $label; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                            <div class="valid-feedback">
                                                <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                            </div>
                                            <div class="invalid-feedback">
                                                <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-4">
                                    <label>
                                        <?php echo $language->getLine('MARITAL'); ?>
                                    </label>
                                    <select name="marital" class="form-control custom-select" required>
                                        <?php foreach($options->maritals as $value => $label): ?>
                                            <option value="<?php echo $value; ?>" <?php echo($value === $post->marital ? 'selected' : ''); ?>>
                                                <?php echo $label; ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                    <div class="valid-feedback">
                                        <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                    </div>
                                    <div class="invalid-feedback">
                                        <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label>
                                        <?php echo $language->getLine('RELIGION'); ?>
                                    </label>
                                    <select name="religion" class="form-control custom-select" required>
                                        <?php foreach($options->religions as $value => $label): ?>
                                            <option value="<?php echo $value; ?>" <?php echo($value === $post->religion ? 'selected' : ''); ?>>
                                                <?php echo $label; ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                    <div class="valid-feedback">
                                        <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                    </div>
                                    <div class="invalid-feedback">
                                        <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label><?php echo $language->getLine('HOBBY'); ?></label>
                                    <input class="form-control" type="text" name="hobby" value="<?=$post->hobby;?>">
                                    <div class="valid-feedback">
                                        <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                    </div>
                                    <div class="invalid-feedback">
                                        <?php echo $language->getLine('PLEASE_INPUT'); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-md">
                                    <h6><?php echo $language->getLine('EYESIGHT_SYNDROME'); ?></h6>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="eyes_sight_left"><?php echo $language->getLine('LEFT_EYE'); ?></label>
                                        <select id="eyes_sight_left" class="form-control" name = "eyes[sight_left]">
                                            <?php foreach ($options->sights as $label => $value):?>
                                                <option value = '<?=$value;?>' <?php if ($post->eyes): ?>

                                                    <?php echo($value === $post->eyes->sight_left ? 'selected' : ''); ?> <?php endif; ?>>
                                                    <?=$label;?>
                                                </option>
                                            <?php endforeach;?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="eyes_value_left"><?php echo $language->getLine('VALUE'); ?></label>

                                        <input id="eyes_value_left" class="form-control" type="number" name ="eyes[value_left]" <?php if ($post->eyes): ?> value="<?=$post->eyes->value_left;?>" <?php endif; ?>>
                                    </div>
                                </div>
                                <div class="col-md">
                                    <div class="form-group">
                                        <label for="eyes_sight_right"><?php echo $language->getLine('RIGHT_EYE'); ?></label>
                                        <select id="eyes_sight_right" class="form-control" name = "eyes[sight_right]">
                                            <?php foreach ($options->sights as $label => $value):?>
                                                <option value = '<?=$value;?>' <?php if ($post->eyes): ?>

                                                    <?php echo($value === $post->eyes->sight_right ? 'selected' : ''); ?> <?php endif; ?>>
                                                    <?=$label;?>
                                                </option>
                                            <?php endforeach;?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $language->getLine('VALUE'); ?></label>
                                        <input class="form-control" type="number"  name = "eyes[value_right]" <?php if ($post->eyes): ?> value="<?=$post->eyes->value_left;?>" <?php endif; ?>>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>