<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form  method="post" action="<?php echo current_url(); ?>">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->header; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                        <div class="card-body pb-1" id="modal-form" data-title="Form Title">
                            <div class="form-group">
                                <label><?php echo $language->getLine('DEPARTMENT'); ?></label>
                                <input name="experiences[<?php /*echo $key;*/ ?>][company_department]" class="form-control" type="text" value="<?php /*echo $experience->company_department;*/ ?>">
                            </div>
                            <div class="form-group">
                                <label><?php echo $language->getLine('POSITION'); ?></label>
                                <input name="experiences[<?php /*echo $key;*/ ?>][company_department_position]" class="form-control" type="text" value="<?php /*echo $experience->company_department_position;*/ ?>">
                            </div>
                            <div class="form-group">
                                <label><?php echo $language->getLine('TENURE'); ?></label>
                                <input type="hidden" name="experiences[<?php /*echo $key;*/ ?>][id]" value="<?php /*echo $experience->id;*/ ?>">
                                <input name="experiences[<?php /*echo $key;*/ ?>][date]" class="form-control daterange-datepicker" type="text" value="<?php /*echo $experience->date_start;*/ ?> - <?php /*echo $experience->date_end;*/ ?>">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
