<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form  method="post" action="<?php echo current_url(); ?>">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->header; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-default">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
                            <input type="hidden" name="id" value="<?php echo $post->id; ?>">

	                        <div class="row">
		                        <div class="col-md-6">
			                        <div class="form-group">
		                                <label><?php echo $language->getLine('INSTITUTION'); ?></label>
		                                <input class="form-control" type="text" name="institution" value="<?php echo $post->institution; ?>" required>
		                            </div>
		                        </div>
		                        <div class="col-md-6">
			                        <label><?php echo $language->getLine('STAGE'); ?></label>
	                                <select class="form-control custom-select" name="id_education_stage" required>
	                                    <?php foreach($options->stages as $stage): ?>
		                                <option value="<?php echo $stage->id; ?>" <?php echo($stage->id == $post->id_education_stage ? 'selected' : ''); ?>>
	                                            <?php echo $stage->name; ?>
	                                        </option>
	                                    <?php endforeach; ?>
	                                </select>
		                        </div>
	                        </div>

	                        <h6><?php echo $language->getLine('ACADEMIC'); ?></h6>

	                        <div class="row">
		                        <div class="col-md-4">
			                        <div class="form-group">
		                                <label><?php echo $language->getLine('MAJOR'); ?></label>
		                                <input class="form-control" type="text" name="academic_major" value="<?php echo $post->academic_major; ?>">
		                            </div>
		                        </div>
		                        <div class="col-md-4">
			                        <div class="form-group">
		                                <label><?php echo $language->getLine('TITLE'); ?></label>
		                                <input class="form-control" type="text" name="academic_title" value="<?php echo $post->academic_title; ?>">
		                            </div>
		                        </div>
		                        <div class="col-md-2">
			                         <div class="form-group">
		                                <label><?php echo $language->getLine('YEAR'); ?></label>
		                                <select class="form-control custom-select" name="academic_year" required>
		                                    <?php foreach($options->years as $value => $label): ?>
			                                    <option value="<?php echo $value; ?>" <?php echo($value == $post->academic_year ? 'selected' : ''); ?>>
			                                        <?php echo $label; ?>
		                                        </option>
                                            <?php endforeach; ?>
		                                </select>
		                            </div>
		                        </div>
		                        <div class="col-md-2">
			                        <div class="form-group">
		                                <label><?php echo $language->getLine('GRADUATE'); ?></label>
		                                <select class="form-control custom-select" name="graduated" required>
		                                    <?php foreach($options->boolean as $value => $label): ?>
			                                    <option value="<?php echo $value; ?>" <?php echo($value === $post->graduate ? 'selected' : ''); ?>>
		                                            <?php echo $label; ?>
	                                            </option>
                                            <?php endforeach; ?>
		                                </select>
		                            </div>
		                        </div>
	                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
