<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<form  method="post" action="<?php echo current_url(); ?>">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->header; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-default">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
							<input type="hidden" name="id" value="<?php echo $post->id; ?>">
                            <div class="form-group">
                                <label><?php echo $language->getLine('LANGUAGE'); ?></label>
                                <input class="form-control" type="text" value="<?php echo $post->name; ?>" name="name" required>
                            </div>
                            <div class="form-group">
                                <label><?php echo $language->getLine('READ'); ?></label>
                                <select class="form-control custom-select" name="grade_read" required>
                                    <?php foreach($options->grades as $value => $label): ?>
                                        <option value="<?php echo $value; ?>" <?php echo($value === $post->grade_read ? 'selected' : ''); ?>>
                                            <?php echo $label; ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label><?php echo $language->getLine('WRITE'); ?></label>
                                <select class="form-control custom-select" name="grade_write" required>
                                    <?php foreach($options->grades as $value => $label): ?>
                                        <option value="<?php echo $value; ?>" <?php echo($value === $post->grade_write ? 'selected' : ''); ?>>
                                            <?php echo $label; ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label><?php echo $language->getLine('SPOKE'); ?></label>
                                <select class="form-control custom-select" name="grade_spoke" required>
                                    <?php foreach($options->grades as $value => $label): ?>
                                        <option value="<?php echo $value; ?>" <?php echo($value === $post->grade_spoke ? 'selected' : ''); ?>>
                                            <?php echo $label; ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
