<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form  method="post" action="<?php echo current_url(); ?>">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
							<?php echo $page->header; ?>
							<div class="card-options">
								<button type="button" class="btn btn-default" data-action="cancel">
								<?php echo $language->getLine('BTN_CANCEL'); ?>
								</button>
								<button type="submit" class="btn btn-primary">
								<?php echo $language->getLine('BTN_SAVE'); ?>
								</button>
							</div>
						</h5>
						<div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
							<input type="hidden" name="id" value="<?php echo $post->id; ?>">
							<div class="container">
								<div class="row">
									<div class="col-12">
										<div class="form-group">
											<label class="d-block"><?php echo $language->getLine('ID_NUMBER'); ?></label>
											<input class="form-control" type="text" name="number" value="<?=$post->number;?>">
										</div>
									</div>
									<div class="col-6">
										<div class="form-group">
											<label class="d-block"><?php echo $language->getLine('TYPE'); ?></label>
											<select class="form-control" name = "type">
                                                <?php $type = ['Citizen ship' => 'CITIZEN SHIP', 'Taxpayer' => 'TAXPAYER', 'Passport' => 'PASSPORT'];?>
                                                <?php foreach($type as $value => $label):?>
                                                    <option value="<?=$label;?>" <?=($label == $post->type ? 'selected' : '')?>>
                                                        <?php echo $language->getLine($label); ?>
                                                    </option>
                                                <?php endforeach;?>
											</select>
										</div>
									</div>
									<div class="col-6">
										<div class="form-group mb-0">
											<label class="d-block"><?php echo $language->getLine('EXPIRED_DATE'); ?></label>
											<input class="form-control" type="date" value ="<?=$post->valid_until;?>" name="valid_until">
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-12">
										<div class="form-group mb-0">
											<label class="d-block"><?php echo $language->getLine('UPLOAD_FILE'); ?></label>
											<div class="form-group">
				                                <input type="file" value = "<?=$post->photo;?>" name="photo" class="dropify" data-height="130" data-default-file="<?php echo (empty($post->photo) ? images_url('default/avatar.jpg') : $post->image); ?>" data-allowed-file-extensions="jpg png" />
				                            </div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>