<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form  method="post" action="<?php echo current_url(); ?>" enctype="multipart/form-data">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
							<?php echo $page->header; ?>
							<div class="card-options">
								<button type="button" class="btn btn-default" data-action="cancel">
								<?php echo $language->getLine('BTN_CANCEL'); ?>
								</button>
								<button type="submit" class="btn btn-primary">
								<?php echo $language->getLine('BTN_SAVE'); ?>
								</button>
							</div>
						</h5>
						<div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
							<input type="hidden" name="id" value="<?php echo $post->id; ?>">
							<div class="container">
								<div class="row">
									<div class="col-12">
										<div class="form-group">
											<label class="d-block"><?php echo $language->getLine('LABEL'); ?></label>
											<input class="form-control" type="text" name="label" value="<?php echo $post->label; ?>">
										</div>
									</div>
									<div class="col-6">
										<div class="form-group">
											<label class="d-block"><?php echo $language->getLine('NUMBER'); ?></label>
											<input class="form-control" type="text" name="number" value="<?php echo $post->number; ?>">
										</div>
									</div>
									<div class="col-6">
										<div class="form-group mb-0">
											<label class="d-block"><?php echo $language->getLine('LIMIT'); ?></label>
											<input class="form-control" type="number" name="limit" value="<?php echo $post->limit; ?>">
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-12">
										<div class="form-group mb-0">
											<label class="d-block"><?php echo $language->getLine('UPLOAD_FILE'); ?></label>
											<div class="form-group">
				                                <input value="<?php echo $post->image; ?>" type="file" name="photo" class="dropify" data-height="130" data-default-file="<?php echo (empty($post->image) ? images_url('avatar.jpg') : base_url('storage/images/employee/legals/'.$post->image)); ?>" data-allowed-file-extensions="jpg png" />
				                            </div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>