<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form  method="post" action="<?php echo current_url(); ?>">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
							<?php echo $page->header; ?>
							<div class="card-options">
								<button type="button" class="btn btn-default" data-action="cancel">
								<?php echo $language->getLine('BTN_CANCEL'); ?>
								</button>
								<button type="submit" class="btn btn-primary">
								<?php echo $language->getLine('BTN_SAVE'); ?>
								</button>
							</div>
						</h5>
						<div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
							<form>
                                <div class="form-group mb-0 row">
                                    <div class="col-md-7">
                                        <div class="form-group mb-0">
                                            <input type="hidden" class="form-control" name="id" value="<?=$post->id;?>">
                                            <label><?php echo $language->getLine('ADD_MOBILE_NUMBER'); ?></label>
                                            <div class="input-group row">
                                                <div class="col-md pr-0">
	                                                <input type="text" class="form-control" name="number" value="<?=$post->number;?>">
	                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md">
                                        <div class="form-group mb-0">
                                            <label><?php echo $language->getLine('PRIMARY_MOBILE_NUMBER'); ?></label>
                                            <div class="input-group">
                                                <select class="form-control custom-select" name="primary">
                                                    <option value="YES">YES</option>
                                                    <option value="NO">NO</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>