<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form  method="post" action="<?php echo current_url(); ?>">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->title; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                        <?php if($post->id):?>
                            <input type="hidden" name="id" value="<?=$post->id;?>">
                        <?php endif ;?>
                        <div class="card-body" id="modal-form" data-title="Form Title">
                            <div class="form-group">
                                <label><?php echo $language->getLine('DESIGNATIONS'); ?></label>
                                <select name="id_company_department_designation" class="form-control select-with-search">
                                    <?php if($options->departments):?>
                                    <?php foreach ($options->departments as $department):?>
                                        <optgroup label="<?=$department->name;?>">
                                            <?php if($department->designations):?>
                                            <?php foreach ($department->designations as $designation):?>
                                                <option value="<?=$designation->id;?>">
                                                    <?php echo str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;', $designation->record_depth); ?>
                                                    <?php echo $designation->record_depth == 0 ? '' : '&#8627;'; ?>
                                                    <?php echo $designation->title; ?>
                                                </option>
                                            <?php endforeach ;?>
                                            <?php endif ;?>
                                        </optgroup>
                                    <?php endforeach ;?>
                                    <?php endif;?>
                                </select>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label><?php echo $language->getLine('REQUEST_DATE'); ?></label>
                                        <input type="text" class="form-control datepicker" value="<?=$post->date_request;?>" name="date_request">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label><?php echo $language->getLine('EFFECTIVE_DATE'); ?></label>
                                        <input type="text" class="form-control datepicker" value="<?=$post->date_effective;?>" name="date_effective">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label><?php echo $language->getLine('REMARK'); ?></label>
                                <select name="remark" class="form-control select-with-search">
                                    <?php if($options->remarks):?>
                                    <?php foreach ($options->remarks as $key => $value):?>
                                         <option value="<?=$value;?>"><?=$key;?></option>
                                    <?php endforeach ;?>
                                    <?php endif;?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label><?php echo $language->getLine('NOTE'); ?></label>
                                <textarea name="note" class="form-control"><?=$post->note;?></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <h5 class="card-header"><?php echo $language->getLine('APPROVAL'); ?></h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label><?php echo $language->getLine('RECOMMENDATION'); ?></label>
                                        <select name="approval[recommendation][]" class="select-dropdown form-control" multiple data-style="btn-default" title="Choose" data-live-search="true" data-max-options="3" required>
                                            <option value="" ><?php echo $language->getLine('CHOICE'); ?></option>
                                            <?php if($options->employees):?>
                                            <?php foreach ($options->employees as $employee):?>
                                                <option value="<?=$employee->id;?>"
                                                    <?php if($post->recommendations):?>
                                                        <?php foreach ($post->recommendations as $recommendation):?>
                                                            <?php if($recommendation->id_hr_employee === $employee->id):?>
                                                                selected
                                                            <?php endif ;?>
                                                        <?php endforeach;?>
                                                    <?php endif ;?>
                                                ><?=$employee->name;?></option>
                                            <?php endforeach ;?>
                                            <?php endif ;?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label><?php echo $language->getLine('EXAMINER'); ?></label>
                                        <select name="approval[examiner][]" class="select-dropdown form-control" multiple data-style="btn-default" title="Choose" data-live-search="true" data-max-options="3">
                                            <option value=""><?php echo $language->getLine('CHOICE'); ?></option>
                                            <?php if($options->employees):?>
                                                <?php foreach ($options->employees as $employee):?>
                                                    <option value="<?=$employee->id;?>"
                                                    <?php if($post->examiners):?>
                                                            <?php foreach ($post->examiners as $examiner):?>
                                                            <?php if($examiner->id_hr_employee === $employee->id):?>
                                                            <?php echo $language->getLine('SELECTED'); ?>
                                                            <?php endif ;?>
                                                            <?php endforeach;?>
                                                    <?php endif ;?>
                                                    ><?=$employee->name;?></option>
                                                <?php endforeach ;?>
                                            <?php endif ;?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label><?php echo $language->getLine('APPROVER'); ?></label>
                                        <select name="approval[approver][]" class="select-dropdown form-control" multiple data-style="btn-default" title="Choose" data-live-search="true" data-max-options="3">
                                            <option value=""><?php echo $language->getLine('CHOICE'); ?></option>
                                            <?php if($options->employees):?>
                                                <?php foreach ($options->employees as $employee):?>
                                                    <option value="<?=$employee->id;?>"
                                                        <?php if($post->approvers):?>
                                                            <?php foreach ($post->approvers as $approver):?>
                                                                <?php if($approver->id_hr_employee === $employee->id):?>
                                                                    <?php echo $language->getLine('SELECTED'); ?>
                                                                <?php endif ;?>
                                                            <?php endforeach;?>
                                                        <?php endif ;?>
                                                    ><?=$employee->name;?></option>
                                                <?php endforeach ;?>
                                            <?php endif ;?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
