<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form  method="post" action="<?php echo current_url(); ?>">
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
							<?php echo $page->header; ?>
							<div class="card-options">
								<button type="button" class="btn btn-default" data-action="cancel">
								<?php echo $language->getLine('BTN_CANCEL'); ?>
								</button>
								<button type="submit" class="btn btn-primary">
								<?php echo $language->getLine('BTN_SAVE'); ?>
								</button>
							</div>
						</h5>
						<div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
							<input type="hidden" name="id" value="<?php echo $post->id; ?>">
							<div class="container">
								<div class="row">
									<div class="col-12">
										<div class="form-group">
											<label class="d-block"><?php echo $language->getLine('NAME'); ?></label>
											<input class="form-control" type="text" name="name">
										</div>
									</div>
									<div class="col-6">
										<div class="form-group">
											<label class="d-block"><?php echo $language->getLine('TIME_START'); ?></label>
											<input class="form-control" type="time" name="time_start">
										</div>
									</div>
									<div class="col-6">
										<div class="form-group">
											<label class="d-block"><?php echo $language->getLine('TIME_END'); ?></label>
											<input class="form-control" type="time" name="time_end">
										</div>
									</div>
									<div class="col-12">
										<div class="form-group mb-0">
											<label class="d-block"><?php echo $language->getLine('DATE'); ?></label>
											<input class="form-control" type="date" name="expired_date">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>