`<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form  method="POST" action="<?php echo current_url(); ?>" class="needs-validation" novalidate>
                    <div class="card">
                        <h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->header; ?>
                            <div class="card-options">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
                            <input type="hidden" name="id" value="<?php echo $post->id; ?>">
                            <div class="form-group">
                                <label for="shirt"><?php echo $language->getLine('SHIRTS'); ?></label>
                                <select id="shirt" class="form-control custom-select" name="size_shirt" required>
                                    <?php foreach($options->sizes as $value => $label): ?>
                                        <option value="<?php echo $value; ?>" <?php echo($value === $post->size_shirt ? 'selected' : ''); ?>>
                                            <?php echo $label; ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                                <div class="valid-feedback">
                                    <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                </div>
                                <div class="invalid-feedback">
                                    <?php echo $language->getLine('PLEASE_CHOOSE_A_SIZE'); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="pants"><?php echo $language->getLine('PANTS'); ?></label>
                                <input id="pants" type="text" class="form-control" name="size_pants" value="<?php echo $post->size_pants; ?>" required>
                                <div class="valid-feedback">
                                    <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                </div>
                                <div class="invalid-feedback">
                                    <?php echo $language->getLine('PLEASE_YOUR_SIZE_OF_PANTS'); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="shoes"><?php echo $language->getLine('SHOES'); ?></label>
                                <input id="shoes" type="text" class="form-control" name="size_shoes" value="<?php echo $post->size_shoes; ?>" required>
                                <div class="valid-feedback">
                                    <?php echo $language->getLine('LOOKS_GOOD'); ?>
                                </div>
                                <div class="invalid-feedback">
                                    <?php echo $language->getLine('PLEASE_YOUR_SIZE_OF_SHOES'); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>