<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<form  method="post" action="<?php echo current_url(); ?>" class="needs-validation" novalidate>
					<div class="card">
						<h5 class="card-header d-flex justify-content-between align-items-center">
							<?php echo $page->header; ?>
							<div class="card-options">
								<button type="button" class="btn btn-default" data-action="cancel">
								<?php echo $language->getLine('BTN_CANCEL'); ?>
								</button>
								<button type="submit" class="btn btn-default">
								<?php echo $language->getLine('BTN_SAVE'); ?>
								</button>
							</div>
						</h5>
						<div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
							<input type="hidden" name="id" value="<?php echo $post->id; ?>">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label for="organizer"><?php echo $language->getLine('ORGANIZER'); ?></label>
										<input id="organizer" name="organizer" class="form-control" type="text" value="<?php echo $post->organizer; ?>" required>
                                        <div class="valid-feedback">
                                            Looks Good
                                        </div>
                                        <div class="invalid-feedback">
                                            Please input a name organizer
                                        </div>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label for="name"><?php echo $language->getLine('NAME'); ?></label>
										<input id="name" name="name" class="form-control" type="text" value="<?php echo $post->name; ?>" required>
                                        <div class="valid-feedback">
                                            Looks Good
                                        </div>
                                        <div class="invalid-feedback">
                                            Please input a name organizer
                                        </div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label for="date"><?php echo $language->getLine('DATE'); ?></label>
										<input id="date" name="date" class="form-control" type="date" value="<?php echo $post->date; ?>" required>
                                        <div class="valid-feedback">
                                            Looks Good
                                        </div>
                                        <div class="invalid-feedback">
                                            Please input a name organizer
                                        </div>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label for="certified"><?php echo $language->getLine('CERTIFIED'); ?></label>
										<select id="certified" class="form-control custom-select" name="certified" required>
											<?php foreach($options->boolean as $value => $label): ?>
												<option value="<?php echo $value; ?>" <?php echo($value === $post->certified ? 'selected' : ''); ?>>
												<?php echo $label; ?>
											</option>
                                            <?php endforeach; ?>
										</select>
                                        <div class="valid-feedback">
                                            Looks Good
                                        </div>
                                        <div class="invalid-feedback">
                                            Please input a name organizer
                                        </div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-12">
									<div class="form-group mb-0">
										<label class="d-block"><?php echo $language->getLine('UPLOAD_CERTIFICATE'); ?></label>
										<div class="form-group">
			                                <input type="file" name="photo" class="dropify" data-height="130" data-default-file="<?php echo (empty($post->photo) ? images_url('default/avatar.jpg') : $post->image); ?>" data-allowed-file-extensions="jpg png" />
			                            </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>