<!DOCTYPE html>
<html>
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {{$assets->head}}
</head>
<body class="admin-ui fix-header fix-sidebar">
    <header class="header">
        {{$partials->header}}
    </header>

    <aside class="sidebar">
        {{$partials->sidebar}}
    </aside>

    <main class="main">
        <div class="container-fluid">
            {{$partials->content}}
        </div>
    </main>
{{$assets->body}}
</body>
</html>