<div class="row justify-content-center">
    <div class="col-lg-6 col-md-7">
        <ul class="step">
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">1</a>
                </div>
            </li>
            <li>
                <div class="wrap">
                    <a href="javascript:void(0);">2</a>
                </div>
            </li>
            <li>
                <div class="wrap">
                    <a href="javascript:void(0);">3</a>
                </div>
            </li>
            <li>
                <div class="wrap">
                    <a href="javascript:void(0);">4</a>
                </div>
            </li>
        </ul>
        <div class="card">
            <div class="card-body">
                <p>Welcome to WordPress. Before getting started, we need some information on the database. You will need to know the following items before proceeding.</p>
                <ol class="pl-3">
                    <li>Database name</li>
                    <li>Database username</li>
                    <li>Database password</li>
                    <li>Database host</li>
                    <li>Table prefix (if you want to run more than one WordPress in a single database)</li>
                </ol>
                <p>We’re going to use this information to create a <code>wp-config.php</code> file.	<strong>If for any reason this automatic file creation doesn’t work, don’t worry. All this does is fill in the database information to a configuration file. You may also simply open <code>wp-config-sample.php</code> in a text editor, fill in your information, and save it as <code>wp-config.php</code>.</strong>
                Need more help? <a href="https://codex.wordpress.org/Editing_wp-config.php">We got it</a>.</p>
                <div class="text-right">
                    <a href="javascript:void(0);" class="btn btn-primary">Let's go!</a>
                </div>
            </div>
        </div>
    </div>
</div>