<div class="row justify-content-center">
    <div class="col-lg-6 col-md-7">
        <ul class="step">
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">1</a>
                </div>
            </li>
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">2</a>
                </div>
            </li>
            <li>
                <div class="wrap">
                    <a href="javascript:void(0);">3</a>
                </div>
            </li>
            <li>
                <div class="wrap">
                    <a href="javascript:void(0);">4</a>
                </div>
            </li>
        </ul>
        <div class="card">
            <div class="card-body">
                <p>Below you should enter your database connection details. If you’re not sure about these, contact your host.</p>
                <form>
                    <div class="row justify-content-center">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Database Name</label>
                                <input type="text" class="form-control">
                                <small class="form-text text-muted">The name of the database you want to use with WordPress.</small>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control">
                                <small class="form-text text-muted">Your database username.</small>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control">
                                <small class="form-text text-muted">Your database password.</small>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Database Host</label>
                                <input type="text" class="form-control">
                                <small class="form-text text-muted">You should be able to get this info from your web host, if <code>localhost</code> doesn’t work.</small>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Table Prefix</label>
                                <input type="text" class="form-control">
                                <small class="form-text text-muted">If you want to run multiple WordPress installations in a single database, change this.</small>
                            </div>
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>