<div class="row justify-content-center">
    <div class="col-lg-6 col-md-7">
        <ul class="step">
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">1</a>
                </div>
            </li>
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">2</a>
                </div>
            </li>
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">3</a>
                </div>
            </li>
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">4</a>
                </div>
            </li>
        </ul>
        <div class="card">
            <div class="card-body">
                <h5>Welcome</h5>
                <p>Welcome to the famous five-minute WordPress installation process! Just fill in the information below and you’ll be on your way to using the most extendable and powerful personal publishing platform in the world.</p>
                <hr>
                <h5>Information needed</h5>
                <p>Please provide the following information. Don’t worry, you can always change these settings later.</p>
                <form>
                    <div class="row justify-content-center">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Site Title</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control">
                                <small class="form-text text-muted">Usernames can have only alphanumeric characters, spaces, underscores, hyphens, periods, and the @ symbol.</small>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control">
                                <small class="form-text text-muted"><strong>Important:</strong> You will need this password to log in. Please store it in a secure location.</small>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Your Email</label>
                                <input type="email" class="form-control">
                                <small class="form-text text-muted">Double-check your email address before continuing.</small>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Search Engine Visibility</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                                    <label class="form-check-label" for="defaultCheck1">
                                        Discourage search engines from indexing this site
                                    </label>
                                </div>
                                <small class="form-text text-muted">It is up to search engines to honor this request.</small>
                            </div>
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Install Nitro</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>