<div class="row justify-content-center">
    <div class="col-lg-6 col-md-7">
        <ul class="step">
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">1</a>
                </div>
            </li>
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">2</a>
                </div>
            </li>
            <li class="active">
                <div class="wrap">
                    <a href="javascript:void(0);">3</a>
                </div>
            </li>
            <li>
                <div class="wrap">
                    <a href="javascript:void(0);">4</a>
                </div>
            </li>
        </ul>
        <div class="card">
            <div class="card-body">
                <p>All right, sparky! You’ve made it through this part of the installation. WordPress can now communicate with your database. If you are ready, time now to…</p>
                
                <div class="text-right">
                    <a href="javascript:void(0);" class="btn btn-primary">Run the installation</a>
                </div>
            </div>
        </div>
    </div>
</div>