<div class="row justify-content-center">
    <div class="col-lg-6 col-md-7">
        <div class="card">
            <div class="card-body">
                <h5>Success</h5>
                <p>WordPress has been installed. Thank you, and enjoy!</p>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label font-weight-bold">Username</label>
                    <div class="col-sm-8">
                        <input type="text" readonly class="form-control-plaintext" value="admin">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label font-weight-bold">Password</label>
                    <div class="col-sm-8">
                        <input type="text" readonly class="form-control-plaintext" value="Your chosen password.">
                    </div>
                </div>
                <div class="text-right">
                    <a href="javascript:void(0);" class="btn btn-primary">Log In</a>
                </div>
            </div>
        </div>
    </div>
</div>