<!DOCTYPE html>
<html>
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {{ $assets->head }}
</head>
<body class="venus-admin venus-customizer">
    <form>
        <aside class="sidebar-left sidebar-customizer">
            {{$partials->sidebar}}
        </aside>
        <main class="main">
            <div class="main-customize">
                <iframe src="{{domain_url()}}" width="100%" height="100%"></iframe>
            </div>
        </main>
    </form>

    {{ $assets->body }}
</body>
</html>