<!DOCTYPE html>
<html>
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Font-->
    {{ $assets->head }}
</head>
<body class="nitro-admin">
    <div id="page-wrapper">
        <header class="header">
            {{$partials->header}}
        </header>
        <aside class="aside aside-left">
            {{$partials->sidebar}}
        </aside>
        <main class="main" id="main">
            {{$partials->content}}
        </main>
    </div>
    {{ $assets->body }}
</body>
</html>
