<div class="account-page">

    {{$page->menus->cover}}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="card card-widget">
                    <div class="card-body bg-primary">
                        <div class="icon"><i class="fa fa-arrows-alt"></i></div>
                        <div class="num">567</div>
                        <h3>Open Tasks</h3>
                        <a href="javascript:void(0);" class="info">Manage <i class="fa fa-chevron-circle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-widget">
                    <div class="card-body bg-danger">
                        <div class="icon"><i class="fa fa-times-circle"></i></div>
                        <div class="num">67</div>
                        <h3>Closed Tasks</h3>
                        <a href="javascript:void(0);" class="info">Manage <i class="fa fa-chevron-circle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-widget">
                    <div class="card-body bg-success">
                        <div class="icon"><i class="fa fa-check-circle"></i></div>
                        <div class="num">500</div>
                        <h3>Completed Tasks</h3>
                        <a href="javascript:void(0);" class="info">Manage <i class="fa fa-chevron-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <ol class="sortable personal-tasks">
                    <li>
                        <div class="card">
                            <div class="card-header">
                                <div class="checkbox">
                                    <input id="checkbox0" type="checkbox">
                                    <label for="checkbox0">&nbsp;</label>
                                </div>
                                <span class="title">Task Title, Really Personal</span>
                                <span class="action">
                                    <span data-toggle="tooltip" title="Edit Task">
                                        <a href="javascript:void(0);" data-toggle="collapse" data-target="#edit-task"><i class="fa fa-pencil"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" title="Add Subtask">
                                        <a href="javascript:void(0);" data-toggle="collapse" data-target="#add-subtask"><i class="fa fa-indent"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" title="Priority">
                                        <a href="javascript:void(0);"><i class="fa fa-exclamation-circle"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" title="Time">
                                        <a href="javascript:void(0);"><i class="fa fa-clock-o"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" title="Progress">
                                        <a href="javascript:void(0);">0%</a>
                                    </span>
                                    <span data-toggle="tooltip" title="Reminder">
                                        <a href="javascript:void(0);"><i class="fa fa-bell"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" title="Followers">
                                        <a href="javascript:void(0);"><i class="fa fa-eye"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" title="Add Comment">
                                        <a href="javascript:void(0);"><i class="fa fa-comments"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" title="View Detail">
                                        <a href="javascript:void(0);"><i class="fa fa-search-plus"></i></a>
                                    </span>
                                </span>
                            </div>
                            <div class="card-body collapse" id="edit-task">
                                <ul class="nav nav-tabs tabs">
                                    <li class="nav-item">
                                        <a href="#who" class="nav-link active" data-toggle="tab">
                                            <i class="fa fa-user" data-toggle="tooltip" title="Who & When"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#description" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-align-left" data-toggle="tooltip" title="Description"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#files" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-paperclip" data-toggle="tooltip" title="Files"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#privacy" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-lock" data-toggle="tooltip" title="Privacy"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#priority" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-exclamation-circle" data-toggle="tooltip" title="Priority"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#progress" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-clock-o" data-toggle="tooltip" title="Progress & Time"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#followers" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-eye" data-toggle="tooltip" title="Followers"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#dependencies" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-level-up" data-toggle="tooltip" title="Dependencies"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#repeat" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-repeat" data-toggle="tooltip" title="Repeat"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#reminder" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-bell" data-toggle="tooltip" title="Reminder"></i>
                                        </a>
                                    </li>
                                </ul>

                                <div class="tab-content tabs p-3">
                                    <div class="tab-pane active" id="who">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Who should do this?</label>
                                                <select class="form-control custom-select">
                                                    <option value="">Jane</option>
                                                    <option value="">Do</option>
                                                </select>
                                            </div>
                                            <div class="form-group col-sm-4">
                                                <label>Start Date</label>
                                                <div class="input-group">
                                                    <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                </div>
                                            </div>
                                            <div class="form-group col-sm-4">
                                                <label>Due Date</label>
                                                <div class="input-group">
                                                    <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="description">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Provide a detailed description for this task <span class="text-muted">(optional)</span></label>
                                                <textarea class="form-control"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="files">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Would you like to attach files to this task?</label>
                                                <div class="dropzone" id="dropzone-wrap">
                                                    <div class="fallback">
                                                        <input name="file" type="file" multiple />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="privacy">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Privacy — Who can see this task?</label>
                                                <select class="form-control custom-select">
                                                    <option value="">Everyone</option>
                                                    <option value="">Private</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="priority">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Choose the priority of this task</label>
                                                <select class="form-control custom-select">
                                                    <option value="">None</option>
                                                    <option value="">Low</option>
                                                    <option value="">Medium</option>
                                                    <option value="">High</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="progress">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Progress so far (0%)</label>
                                            </div>
                                            <div class="form-group col-sm-4">
                                                <label>Estimated time to complete</label>
                                                <div class="input-group" role="group">
                                                    <span class="input-group-addon">Hours</span>
                                                    <input class="form-control" placeholder="0">
                                                    <span class="input-group-addon">Minutes</span>
                                                    <input class="form-control" placeholder="0">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="followers">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Who will get notifications about activity on this task?</label>
                                                <div class="checkbox">
                                                    <input id="checkbox1" type="checkbox">
                                                    <label for="checkbox1">Select All</label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox2" type="checkbox">
                                                    <label for="checkbox2">Jane</label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox3" type="checkbox">
                                                    <label for="checkbox3">Doe</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="dependencies">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Are there tasks that must be done first?</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="repeat">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Choose the priority of this task</label>
                                                <select class="form-control custom-select">
                                                    <option value="">Does not repat</option>
                                                    <option value="">Daily</option>
                                                    <option value="">Every Weekday</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="reminder">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Reminder for this task</label>
                                                <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                            <div class="card-body collapse" id="add-subtask">
                                <div class="form-row">
                                    <div class="form-group col-sm-6">
                                        <label>What needs to be done?</label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div>
                                <ul class="nav nav-tabs tabs">
                                    <li class="nav-item">
                                        <a href="#who2" class="nav-link active" data-toggle="tab">
                                            <i class="fa fa-user" data-toggle="tooltip" title="Who & When"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#description2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-align-left" data-toggle="tooltip" title="Description"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#files2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-paperclip" data-toggle="tooltip" title="Files"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#privacy2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-lock" data-toggle="tooltip" title="Privacy"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#priority2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-exclamation-circle" data-toggle="tooltip" title="Priority"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#progress2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-clock-o" data-toggle="tooltip" title="Progress & Time"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#followers2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-eye" data-toggle="tooltip" title="Followers"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#dependencies2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-level-up" data-toggle="tooltip" title="Dependencies"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#repeat2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-repeat" data-toggle="tooltip" title="Repeat"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#reminder2" class="nav-link" data-toggle="tab">
                                            <i class="fa fa-bell" data-toggle="tooltip" title="Reminder"></i>
                                        </a>
                                    </li>
                                </ul>

                                <div class="tab-content tabs p-3">
                                    <div class="tab-pane active" id="who2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Who should do this?</label>
                                                <select class="form-control custom-select">
                                                    <option value="">Jane</option>
                                                    <option value="">Do</option>
                                                </select>
                                            </div>
                                            <div class="form-group col-sm-4">
                                                <label>Start Date</label>
                                                <div class="input-group">
                                                    <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                </div>
                                            </div>
                                            <div class="form-group col-sm-4">
                                                <label>Due Date</label>
                                                <div class="input-group">
                                                    <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="description2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Provide a detailed description for this task <span class="text-muted">(optional)</span></label>
                                                <textarea class="form-control"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="files2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Would you like to attach files to this task?</label>
                                                <div class="dropzone" id="dropzone-wrap">
                                                    <div class="fallback">
                                                        <input name="file" type="file" multiple />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="privacy2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Privacy — Who can see this task?</label>
                                                <select class="form-control custom-select">
                                                    <option value="">Everyone</option>
                                                    <option value="">Private</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="priority2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Choose the priority of this task</label>
                                                <select class="form-control custom-select">
                                                    <option value="">None</option>
                                                    <option value="">Low</option>
                                                    <option value="">Medium</option>
                                                    <option value="">High</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="progress2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Progress so far (0%)</label>
                                            </div>
                                            <div class="form-group col-sm-4">
                                                <label>Estimated time to complete</label>
                                                <div class="input-group" role="group">
                                                    <span class="input-group-addon">Hours</span>
                                                    <input class="form-control" placeholder="0">
                                                    <span class="input-group-addon">Minutes</span>
                                                    <input class="form-control" placeholder="0">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="followers2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Who will get notifications about activity on this task?</label>
                                                <div class="checkbox">
                                                    <input id="checkbox1" type="checkbox">
                                                    <label for="checkbox1">Select All</label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox2" type="checkbox">
                                                    <label for="checkbox2">Jane</label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox3" type="checkbox">
                                                    <label for="checkbox3">Doe</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="dependencies2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-12">
                                                <label>Are there tasks that must be done first?</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="repeat2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Choose the priority of this task</label>
                                                <select class="form-control custom-select">
                                                    <option value="">Does not repat</option>
                                                    <option value="">Daily</option>
                                                    <option value="">Every Weekday</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="reminder2">
                                        <div class="form-row">
                                            <div class="form-group col-sm-4">
                                                <label>Reminder for this task</label>
                                                <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                        <ol>
                            <li>
                                <div class="card">
                                    <div class="card-header">
                                        <div class="checkbox">
                                            <input id="checkbox-sub1" type="checkbox">
                                            <label for="checkbox-sub1">&nbsp;</label>
                                        </div>
                                        <span class="title">Task Title, Really Personal</span>
                                        <span class="action">
                                            <span data-toggle="tooltip" title="Edit Task">
                                                <a href="javascript:void(0);" data-toggle="collapse" data-target="#edit-task"><i class="fa fa-pencil"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Add Subtask">
                                                <a href="javascript:void(0);" data-toggle="collapse" data-target="#add-subtask"><i class="fa fa-indent"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Priority">
                                                <a href="javascript:void(0);"><i class="fa fa-exclamation-circle"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Time">
                                                <a href="javascript:void(0);"><i class="fa fa-clock-o"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Progress">
                                                <a href="javascript:void(0);">0%</a>
                                            </span>
                                            <span data-toggle="tooltip" title="Reminder">
                                                <a href="javascript:void(0);"><i class="fa fa-bell"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Followers">
                                                <a href="javascript:void(0);"><i class="fa fa-eye"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Add Comment">
                                                <a href="javascript:void(0);"><i class="fa fa-comments"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="View Detail">
                                                <a href="javascript:void(0);"><i class="fa fa-search-plus"></i></a>
                                            </span>
                                        </span>
                                    </div>
                                    <div class="card-body collapse" id="edit-task">
                                        <ul class="nav nav-tabs tabs">
                                            <li class="nav-item">
                                                <a href="#who" class="nav-link active" data-toggle="tab">
                                                    <i class="fa fa-user" data-toggle="tooltip" title="Who & When"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#description" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-align-left" data-toggle="tooltip" title="Description"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#files" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-paperclip" data-toggle="tooltip" title="Files"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#privacy" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-lock" data-toggle="tooltip" title="Privacy"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#priority" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-exclamation-circle" data-toggle="tooltip" title="Priority"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#progress" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-clock-o" data-toggle="tooltip" title="Progress & Time"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#followers" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-eye" data-toggle="tooltip" title="Followers"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#dependencies" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-level-up" data-toggle="tooltip" title="Dependencies"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#repeat" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-repeat" data-toggle="tooltip" title="Repeat"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#reminder" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-bell" data-toggle="tooltip" title="Reminder"></i>
                                                </a>
                                            </li>
                                        </ul>

                                        <div class="tab-content tabs p-3">
                                            <div class="tab-pane active" id="who">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Who should do this?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Jane</option>
                                                            <option value="">Do</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Start Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Due Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="description">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Provide a detailed description for this task <span class="text-muted">(optional)</span></label>
                                                        <textarea class="form-control"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="files">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Would you like to attach files to this task?</label>
                                                        <div class="dropzone" id="dropzone-wrap">
                                                            <div class="fallback">
                                                                <input name="file" type="file" multiple />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="privacy">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Privacy — Who can see this task?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Everyone</option>
                                                            <option value="">Private</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="priority">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">None</option>
                                                            <option value="">Low</option>
                                                            <option value="">Medium</option>
                                                            <option value="">High</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="progress">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Progress so far (0%)</label>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Estimated time to complete</label>
                                                        <div class="input-group" role="group">
                                                            <span class="input-group-addon">Hours</span>
                                                            <input class="form-control" placeholder="0">
                                                            <span class="input-group-addon">Minutes</span>
                                                            <input class="form-control" placeholder="0">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="followers">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Who will get notifications about activity on this task?</label>
                                                        <div class="checkbox">
                                                            <input id="checkbox1" type="checkbox">
                                                            <label for="checkbox1">Select All</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox2" type="checkbox">
                                                            <label for="checkbox2">Jane</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox3" type="checkbox">
                                                            <label for="checkbox3">Doe</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="dependencies">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Are there tasks that must be done first?</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="repeat">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Does not repat</option>
                                                            <option value="">Daily</option>
                                                            <option value="">Every Weekday</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="reminder">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Reminder for this task</label>
                                                        <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                    <div class="card-body collapse" id="add-subtask">
                                        <div class="form-row">
                                            <div class="form-group col-sm-6">
                                                <label>What needs to be done?</label>
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <ul class="nav nav-tabs tabs">
                                            <li class="nav-item">
                                                <a href="#who2" class="nav-link active" data-toggle="tab">
                                                    <i class="fa fa-user" data-toggle="tooltip" title="Who & When"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#description2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-align-left" data-toggle="tooltip" title="Description"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#files2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-paperclip" data-toggle="tooltip" title="Files"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#privacy2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-lock" data-toggle="tooltip" title="Privacy"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#priority2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-exclamation-circle" data-toggle="tooltip" title="Priority"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#progress2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-clock-o" data-toggle="tooltip" title="Progress & Time"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#followers2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-eye" data-toggle="tooltip" title="Followers"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#dependencies2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-level-up" data-toggle="tooltip" title="Dependencies"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#repeat2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-repeat" data-toggle="tooltip" title="Repeat"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#reminder2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-bell" data-toggle="tooltip" title="Reminder"></i>
                                                </a>
                                            </li>
                                        </ul>

                                        <div class="tab-content tabs p-3">
                                            <div class="tab-pane active" id="who2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Who should do this?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Jane</option>
                                                            <option value="">Do</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Start Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Due Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="description2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Provide a detailed description for this task <span class="text-muted">(optional)</span></label>
                                                        <textarea class="form-control"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="files2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Would you like to attach files to this task?</label>
                                                        <div class="dropzone" id="dropzone-wrap">
                                                            <div class="fallback">
                                                                <input name="file" type="file" multiple />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="privacy2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Privacy — Who can see this task?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Everyone</option>
                                                            <option value="">Private</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="priority2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">None</option>
                                                            <option value="">Low</option>
                                                            <option value="">Medium</option>
                                                            <option value="">High</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="progress2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Progress so far (0%)</label>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Estimated time to complete</label>
                                                        <div class="input-group" role="group">
                                                            <span class="input-group-addon">Hours</span>
                                                            <input class="form-control" placeholder="0">
                                                            <span class="input-group-addon">Minutes</span>
                                                            <input class="form-control" placeholder="0">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="followers2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Who will get notifications about activity on this task?</label>
                                                        <div class="checkbox">
                                                            <input id="checkbox1" type="checkbox">
                                                            <label for="checkbox1">Select All</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox2" type="checkbox">
                                                            <label for="checkbox2">Jane</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox3" type="checkbox">
                                                            <label for="checkbox3">Doe</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="dependencies2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Are there tasks that must be done first?</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="repeat2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Does not repat</option>
                                                            <option value="">Daily</option>
                                                            <option value="">Every Weekday</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="reminder2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Reminder for this task</label>
                                                        <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="card">
                                    <div class="card-header">
                                        <div class="checkbox">
                                            <input id="checkbox-sub2" type="checkbox">
                                            <label for="checkbox-sub-2">&nbsp;</label>
                                        </div>
                                        <span class="title">Task Title, Really Personal</span>
                                        <span class="action">
                                            <span data-toggle="tooltip" title="Edit Task">
                                                <a href="javascript:void(0);" data-toggle="collapse" data-target="#edit-task"><i class="fa fa-pencil"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Add Subtask">
                                                <a href="javascript:void(0);" data-toggle="collapse" data-target="#add-subtask"><i class="fa fa-indent"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Priority">
                                                <a href="javascript:void(0);"><i class="fa fa-exclamation-circle"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Time">
                                                <a href="javascript:void(0);"><i class="fa fa-clock-o"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Progress">
                                                <a href="javascript:void(0);">0%</a>
                                            </span>
                                            <span data-toggle="tooltip" title="Reminder">
                                                <a href="javascript:void(0);"><i class="fa fa-bell"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Followers">
                                                <a href="javascript:void(0);"><i class="fa fa-eye"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="Add Comment">
                                                <a href="javascript:void(0);"><i class="fa fa-comments"></i></a>
                                            </span>
                                            <span data-toggle="tooltip" title="View Detail">
                                                <a href="javascript:void(0);"><i class="fa fa-search-plus"></i></a>
                                            </span>
                                        </span>
                                    </div>
                                    <div class="card-body collapse" id="edit-task">
                                        <ul class="nav nav-tabs tabs">
                                            <li class="nav-item">
                                                <a href="#who" class="nav-link active" data-toggle="tab">
                                                    <i class="fa fa-user" data-toggle="tooltip" title="Who & When"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#description" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-align-left" data-toggle="tooltip" title="Description"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#files" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-paperclip" data-toggle="tooltip" title="Files"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#privacy" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-lock" data-toggle="tooltip" title="Privacy"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#priority" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-exclamation-circle" data-toggle="tooltip" title="Priority"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#progress" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-clock-o" data-toggle="tooltip" title="Progress & Time"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#followers" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-eye" data-toggle="tooltip" title="Followers"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#dependencies" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-level-up" data-toggle="tooltip" title="Dependencies"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#repeat" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-repeat" data-toggle="tooltip" title="Repeat"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#reminder" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-bell" data-toggle="tooltip" title="Reminder"></i>
                                                </a>
                                            </li>
                                        </ul>

                                        <div class="tab-content tabs p-3">
                                            <div class="tab-pane active" id="who">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Who should do this?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Jane</option>
                                                            <option value="">Do</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Start Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Due Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="description">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Provide a detailed description for this task <span class="text-muted">(optional)</span></label>
                                                        <textarea class="form-control"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="files">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Would you like to attach files to this task?</label>
                                                        <div class="dropzone" id="dropzone-wrap">
                                                            <div class="fallback">
                                                                <input name="file" type="file" multiple />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="privacy">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Privacy — Who can see this task?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Everyone</option>
                                                            <option value="">Private</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="priority">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">None</option>
                                                            <option value="">Low</option>
                                                            <option value="">Medium</option>
                                                            <option value="">High</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="progress">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Progress so far (0%)</label>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Estimated time to complete</label>
                                                        <div class="input-group" role="group">
                                                            <span class="input-group-addon">Hours</span>
                                                            <input class="form-control" placeholder="0">
                                                            <span class="input-group-addon">Minutes</span>
                                                            <input class="form-control" placeholder="0">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="followers">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Who will get notifications about activity on this task?</label>
                                                        <div class="checkbox">
                                                            <input id="checkbox1" type="checkbox">
                                                            <label for="checkbox1">Select All</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox2" type="checkbox">
                                                            <label for="checkbox2">Jane</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox3" type="checkbox">
                                                            <label for="checkbox3">Doe</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="dependencies">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Are there tasks that must be done first?</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="repeat">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Does not repat</option>
                                                            <option value="">Daily</option>
                                                            <option value="">Every Weekday</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="reminder">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Reminder for this task</label>
                                                        <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                    <div class="card-body collapse" id="add-subtask">
                                        <div class="form-row">
                                            <div class="form-group col-sm-6">
                                                <label>What needs to be done?</label>
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <ul class="nav nav-tabs tabs">
                                            <li class="nav-item">
                                                <a href="#who2" class="nav-link active" data-toggle="tab">
                                                    <i class="fa fa-user" data-toggle="tooltip" title="Who & When"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#description2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-align-left" data-toggle="tooltip" title="Description"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#files2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-paperclip" data-toggle="tooltip" title="Files"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#privacy2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-lock" data-toggle="tooltip" title="Privacy"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#priority2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-exclamation-circle" data-toggle="tooltip" title="Priority"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#progress2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-clock-o" data-toggle="tooltip" title="Progress & Time"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#followers2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-eye" data-toggle="tooltip" title="Followers"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#dependencies2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-level-up" data-toggle="tooltip" title="Dependencies"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#repeat2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-repeat" data-toggle="tooltip" title="Repeat"></i>
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="#reminder2" class="nav-link" data-toggle="tab">
                                                    <i class="fa fa-bell" data-toggle="tooltip" title="Reminder"></i>
                                                </a>
                                            </li>
                                        </ul>

                                        <div class="tab-content tabs p-3">
                                            <div class="tab-pane active" id="who2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Who should do this?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Jane</option>
                                                            <option value="">Do</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Start Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Due Date</label>
                                                        <div class="input-group">
                                                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="description2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Provide a detailed description for this task <span class="text-muted">(optional)</span></label>
                                                        <textarea class="form-control"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="files2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Would you like to attach files to this task?</label>
                                                        <div class="dropzone" id="dropzone-wrap">
                                                            <div class="fallback">
                                                                <input name="file" type="file" multiple />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="privacy2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Privacy — Who can see this task?</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Everyone</option>
                                                            <option value="">Private</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="priority2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">None</option>
                                                            <option value="">Low</option>
                                                            <option value="">Medium</option>
                                                            <option value="">High</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="progress2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Progress so far (0%)</label>
                                                    </div>
                                                    <div class="form-group col-sm-4">
                                                        <label>Estimated time to complete</label>
                                                        <div class="input-group" role="group">
                                                            <span class="input-group-addon">Hours</span>
                                                            <input class="form-control" placeholder="0">
                                                            <span class="input-group-addon">Minutes</span>
                                                            <input class="form-control" placeholder="0">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="followers2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Who will get notifications about activity on this task?</label>
                                                        <div class="checkbox">
                                                            <input id="checkbox1" type="checkbox">
                                                            <label for="checkbox1">Select All</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox2" type="checkbox">
                                                            <label for="checkbox2">Jane</label>
                                                        </div>
                                                        <div class="checkbox">
                                                            <input id="checkbox3" type="checkbox">
                                                            <label for="checkbox3">Doe</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="dependencies2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-12">
                                                        <label>Are there tasks that must be done first?</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="repeat2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Choose the priority of this task</label>
                                                        <select class="form-control custom-select">
                                                            <option value="">Does not repat</option>
                                                            <option value="">Daily</option>
                                                            <option value="">Every Weekday</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="reminder2">
                                                <div class="form-row">
                                                    <div class="form-group col-sm-4">
                                                        <label>Reminder for this task</label>
                                                        <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <div class="card">
                            <div class="card-header">Some content</div>
                        </div>

                    </li>
                    <li>
                        <div class="card">
                            <div class="card-header">Some content</div>
                        </div>
                    </li>
                </ol>
            </div>
        </div>

        <div class="table-responsive bg-white mb-3">
            <table class="table table-condensed mb-0">
                <tbody>
                    <tr>
                        <td style="width:25px">
                            <label class="custom-control custom-checkbox" style="margin-right: 0px; min-height: 1rem;">
                              <input type="checkbox" class="custom-control-input">
                              <span class="custom-control-indicator"></span>
                            </label>
                        </td>
                        <td> <i class="fa" style="margin-left: 0px;"></i> <a href="#">Subject Memo or Memo Title</a></td>
                        <td style="text-align: right;"><a href="#"><img src="{{$account->profile->images->avatar}}" class="img-circle" width="20px" alt=""></a></td>
                        <td style="width:25px"><i class="fa fa-sign-in"></i></td>
                    </tr>
                    <tr>
                        <td style="width:25px">
                            <label class="custom-control custom-checkbox" style="margin-right: 0px; min-height: 1rem;">
                              <input type="checkbox" class="custom-control-input">
                              <span class="custom-control-indicator"></span>
                            </label>
                        </td>
                        <td><i class="fa fa-plus-square-o mr-1" data-toggle="tree" style="margin-left: 0px;"></i> <a href="#">Subject Memo or Memo Title</a></td>
                        <td style="text-align: right;"><a href="#"><img src="{{$account->profile->images->avatar}}" class="img-circle" width="20px" alt=""></a><a href="#"><img src="{{$account->profile->images->avatar}}" class="img-circle" width="20px" alt=""></a></td>
                        <td style="width:25px"><i class="fa fa-sign-in"></i></td>
                    </tr>
                    <tr class="hidden">
                        <td style="width:25px">
                            <label class="custom-control custom-checkbox" style="margin-right: 0px; min-height: 1rem;">
                                <input type="checkbox" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                            </label>
                        </td>
                        <td><i class="fa fa-plus-square-o mr-1" data-toggle="tree" style="margin-left: 20px;"></i> <a href="#">Subject Memo or Memo Title</a></td>
                        <td style="text-align: right;"><a href="#"><img src="{{$account->profile->images->avatar}}" class="img-circle" width="20px" alt=""></a><a href="#"><img src="{{$account->profile->images->avatar}}" class="img-circle" width="20px" alt=""></a></td>
                        <td style="width:25px"><i class="fa fa-sign-in"></i></td>
                    </tr>
                    <tr class="hidden">
                        <td style="width:25px">
                            <label class="custom-control custom-checkbox" style="margin-right: 0px; min-height: 1rem;">
                                <input type="checkbox" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                            </label>
                        </td>
                        <td><i class="fa" style="margin-left: 35px;"></i> <a href="#">Subject Memo or Memo Title</a></td>
                        <td style="text-align: right;"><a href="#"><img src="{{$account->profile->images->avatar}}" class="img-circle" width="20px" alt=""></a><a href="#"><img src="{{$account->profile->images->avatar}}" class="img-circle" width="20px" alt=""></a></td>
                        <td style="width:25px"><i class="fa fa-sign-in"></i></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>