<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <nav class="navbar navbar-expand-lg navbar-light account-cover-navbar bg-white p-relative">
                    <button type="button" class="btn btn-default navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbar-22" aria-controls="navbar-22" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-22">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a href="{{base_url('pages/published')}}" class="nav-link active">Published</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/draft')}}" class="nav-link">Draft</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/scheduled')}}" class="nav-link">Scheduled</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/trash')}}" class="nav-link">Trash</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <div class="input-group">
                                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </nav>
            </div>
        </div>
        <div class="post-list">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <h6 class="m-0">Team</h6>
                            <a href="#invite-modal" data-toggle="modal" class="btn btn-default btn-sm"><i class="fas fa-user-plus"></i> Invite
                        </div>
                        <div class="card-body pb-0">
                            <div class="row align-items-center mb-4">
                                <div class="col-10">
                                    <div class="media align-items-center">
                                        <img src="{{$account->profile->images->avatar}}" width="72" height="72" class="mr-3 rounded-circle">
                                        <div class="media-body">
                                            <h4 class="card-title mb-1">
                                                <a href="#">Teguh Rianto</a>
                                            </h4>
                                            <h6 class="card-subtitle mb-1">
                                                <span class="text-lowercase">@teguhrianto</span>
                                            </h6>
                                            <span class="badge badge-dark">Admin</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-2 text-right">
                                    <div class="dropdown show">
                                        <a class="dropdown-toggle custom-dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        </a>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            <a class="dropdown-item" href="#"><i class="fas fa-pencil-alt"></i> Edit</a>
                                            <a class="dropdown-item" href="#"><i class="fa fa-copy"></i> Duplicate</a>
                                            <a class="dropdown-item" href="#"><i class="fa fa-trash"></i> Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row align-items-center mb-4">
                                <div class="col-10">
                                    <div class="media align-items-center">
                                        <img src="{{$account->profile->images->avatar}}" width="72" height="72" class="mr-3 rounded-circle">
                                        <div class="media-body">
                                            <h4 class="card-title mb-1">
                                                <a href="#">Teguh Rianto</a>
                                            </h4>
                                            <h6 class="card-subtitle mb-1">
                                                <span class="text-lowercase">@teguhrianto</span>
                                            </h6>
                                            <span class="badge badge-dark">Admin</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-2 text-right">
                                    <div class="dropdown show">
                                        <a class="dropdown-toggle custom-dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        </a>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            <a class="dropdown-item" href="#"><i class="fas fa-pencil-alt"></i> Edit</a>
                                            <a class="dropdown-item" href="#"><i class="fa fa-copy"></i> Duplicate</a>
                                            <a class="dropdown-item" href="#"><i class="fa fa-trash"></i> Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="invite-modal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="inviteModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form>
                <div class="modal-header">
                    <h5 class="modal-title" id="inviteModal">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Usernames or Emails</label>
                        <input type="text" class="form-control" name="">
                        <small class="form-text text-muted">
                            Want to invite new users to your site? The more the merrier! Invite as many as you want, up to 10 at a time, by adding their email addresses or usernames.
                        </small>
                    </div>
                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control custom-select">
                            <option>Administrator</option>
                        </select>
                    </div>
                    <div class="form-group mb-0">
                        <label>Custom Message</label>
                        <textarea class="form-control"></textarea>
                        <small class="form-text text-muted">
                            (Optional) You can enter a custom message of up to 500 characters that will be included in the invitation to the user(s).
                        </small>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Invite</button>
                </div>
            </form>
        </div>
    </div>
</div>