<!DOCTYPE html>
<html>
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {{ $assets->head }}
</head>
<body class="venus-admin">
    <header class="header">
        {{$partials->header}}
    </header>
    <aside class="sidebar-left">
        {{$partials->sidebar}}
    </aside>
    <main class="main">
        {{$partials->content}}
    </main>
    {{ $assets->body }}
</body>
</html>
