<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {{$assets->head}}
</head>
<body>
<section class="login-register">
    <div class="login-box card bg-transparent border-0">
        <div class="card-body">
            {{$partials->content}}
        </div>

        <div class="card-footer bg-transparent border-0 text-center">
            Copyright &copy; 2011 - {{date('Y')}}, O2System Framework
        </div>
    </div>
</section>

{{$assets->body}}
</body>
</html>