<form id="form-posts" method="post" action="<?php echo base_url('posts/form'); ?>" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <h6 class="card-header">
                    Title
                </h6>
                <div class="card-body">
                    <input type="hidden" name="id" value="<?php echo $post->id; ?>">
                    <input type="hidden" name="id_section" value="1">

                    <div class="form-group row">
                        <div class="col-md-12">
                            <input class="form-control" type="text" name="title" value="<?php echo $post->title; ?>">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="fas fa-link"></i>
                                    </span>
                                </div>
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <?php echo $settings->address; ?>/
                                    </span>
                                </div>
                                <input class="form-control" name="segments" value="<?php echo $post->segments; ?>" type="text">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <h6 class="card-header">
                    Content
                </h6>
                <div class="card-body p-2 post-editor">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <textarea class="form-control tinymce" name="content">
                                <?php echo $post->content; ?>
                            </textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Images
                </div>
                <div class="card-body p-0">
                    <div class="form-group mb-0">
                        <div class="col-md-12 dropzone border-0" id="dropzone-wrap">
                            <div class="fallback">
                                <input name="images" type="file" multiple />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="dze_info" class="hidden">
                <div class="card">
                    <div class="card-header">
                        Uploaded Files Info
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th width="40%">File name</th>
                                    <th width="15%">Size</th>
                                    <th width="15%">Type</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="4"></td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    Search Engine Optimization
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label class="col-md-3 control-label" for="field-1">Metarobot</label>
                        <div class="col-md-9">
                            <?php echo $fields->metarobot($page->meta['robot']); ?>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 control-label" for="field-1">Metatitle</label>
                        <div class="col-md-9">
                            <input class="form-control" name="meta[title]" value="<?php echo $post->meta['title']; ?>" type="text">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 control-label" for="field-5">Metadescription</label>
                        <div class="col-md-9">
                            <textarea class="form-control" cols="5" name="meta[description]">
                                <?php echo $post->meta['description']; ?>
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 control-label" for="field-5">Metakeywords</label>
                        <div class="col-md-9">
                            <input class="tagsinput form-control" data-role="tagsinput" name="meta[keywords]" value="<?php echo $post->meta['keywords']; ?>" type="text">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="control-label">Language</label>
                        <?php echo $fields->language($post->language); ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Format</label>
                        <?php echo $fields->format($post->format); ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Status</label>
                        <?php echo $fields->recordStatus($post->record_status); ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Visibility</label>
                        <?php echo $fields->visibility($post->visibility); ?>
                    </div>
                    <div class="form-group mb-0 text-right">
                        <a class="btn btn-default" href="<?php echo domain_url('posts/' . $post->id); ?>">
                            Preview
                        </a>
                        <button type="submit" class="btn btn-primary ml-2" data-action="save">
                            Save
                        </button>
                    </div>
                </div>
            </div>

            <div class="card">
                <h6 class="card-header">Publishing</h6>
                <div class="card-body">
                    <div class="form-group">
                        <label class="control-label">Start Publishing</label>
                        <input type="datetime-local" name="publish[start]" class="form-control" value="<?php echo format_date($post->publish_start, '%d/%m/%Y %H:%i'); ?>">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Finish Publishing</label>
                        <input type="datetime-local" name="publish[finish]" class="form-control" value="<?php echo format_date($post->publish_finish, '%d/%m/%Y %H:%i'); ?>">
                    </div>
                </div>
            </div>

            <div class="card">
                <h6 class="card-header">
                    Categories
                </h6>
                <div class="card-body">
                    <div class="form-group">
                        <?php $postCategories = []; ?>
                        <?php if(!empty($post->categories)): ?>
                            <?php foreach($post->categories as $category): ?>
                                <?php $postCategories[] = $category->id_section_category; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <div class="checkbox checkbox-primary">
                            <input id="checkbox-uncategorized" type="checkbox" value="0" <?php echo (empty($postCategories) ? 'checked' : ''); ?>>
                            <label for="checkbox-uncategorized"> Uncategorized </label>
                        </div>

                        <?php if(count($categories)): ?>
                            <?php foreach($categories as $category): ?>
                                <div class="checkbox checkbox-primary">
                                    <input id="checkbox-<?php echo $category->segments; ?>" type="checkbox" value="<?php echo $category->id; ?>" <?php echo (in_array($category->id, $postCategories) ? 'checked': ''); ?>>
                                    <label for="checkbox-<?php echo $category->segments; ?>"> <?php echo $category->title; ?> </label>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <div class="card">
                <h6 class="card-header">
                    Tags
                </h6>
                <div class="card-body">
                    <div class="form-group mb-0">
                        <?php foreach($post->tags as $tag): ?>
                            <?php $tags[] = $tag->label; ?>
                        <?php endforeach; ?>
                        <input type="text" name="tags" data-role="tagsinput" value="<?php echo implode(',', $tags); ?>" />
                    </div>
                </div>
            </div>

            <div class="card">
                <h6 class="card-header">Sharing</h6>
                <div class="card-body">
                    <div class="form-group d-flex justify-content-between">
                        <label class="mb-0">Show sharing buttons</label>
                        <input name="settings[show_share]" type="checkbox" data-size="small" class="js-switch" data-color="#009efb" <?php echo ($post->settings['show_share'] === 'on' ? 'checked' : ''); ?>/>
                    </div>
                    <div class="form-group d-flex justify-content-between">
                        <label class="mb-0">Show like button</label>
                        <input name="settings[show_like]" type="checkbox" data-size="small" class="js-switch" data-color="#009efb" <?php echo ($post->settings['show_like'] === 'on' ? 'checked' : ''); ?>/>
                    </div>
                </div>
            </div>

            <div class="card">
                <h6 class="card-header">More Options</h6>
                <div class="card-body">
                    <div class="form-group">
                        <label>Excerpt</label>
                        <textarea name="excerpt" class="form-control" placeholder="Write an excerpt"><?php echo $post->excerpt; ?></textarea>
                    </div>
                    <div class="form-group d-flex justify-content-between">
                        <label class="mb-0">Featured</label>
                        <input name="featured" type="checkbox" data-size="small" class="js-switch" data-color="#009efb" <?php echo ($post->featured === 'YES' ? 'checked' : ''); ?>/>
                    </div>
                    <div class="form-group mb-0">
                        <label class="text-muted small">DISCUSSION</label>
                    </div>
                    <div class="form-group d-flex justify-content-between">
                        <label class="mb-0">Allow Comments</label>
                        <input name="settings[allow_comments]" type="checkbox" data-size="small" class="js-switch" data-color="#009efb" <?php echo ($post->settings['allow_comments'] === 'on' ? 'checked' : ''); ?>/>
                    </div>
                    <div class="form-group d-flex justify-content-between mb-0">
                        <label class="mb-0">Allow Pingbacks &amp; Trackbacks</label>
                        <input name="settings[allow_trackbacks]" type="checkbox" data-size="small" class="js-switch" data-color="#009efb" <?php echo ($post->settings['allow_trackbacks'] === 'on' ? 'checked' : ''); ?>/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>