<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <nav class="navbar navbar-expand-lg navbar-light page-navbar bg-white p-relative">
                    <button type="button" class="btn btn-default navbar-toggler navbar-toggler-right"
                            data-toggle="collapse" data-target="#navbar-22" aria-controls="navbar-22"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-22">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item <?php echo (in_array(input()->get('status'), [null, 'PUBLISH']) ? 'active' : ''); ?>">
                                <a href="<?php echo base_url('posts', ['status' => 'PUBLISH']); ?>"
                                   class="nav-link active">Published</a>
                            </li>
                            <li class="nav-item <?php echo (input()->get('status') === 'DRAFT' ? 'active' : ''); ?>">
                                <a href="<?php echo base_url('posts', ['status' => 'DRAFT']); ?>" class="nav-link">Drafts</a>
                            </li>
                            <li class="nav-item <?php echo (input()->get('status') === 'TRASH' ? 'active' : ''); ?>">
                                <a href="<?php echo base_url('posts', ['status' => 'TRASH']); ?>" class="nav-link">Trashes</a>
                            </li>
                        </ul>
                        <form id="form-search" class="form-inline my-2 my-lg-0" method="get">
                            <div class="input-group">
                                <input class="form-control" type="search" aria-label="search" name="q" value="<?php echo $input->get('q'); ?>">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </nav>
            </div>
        </div>

        <div class="post-list">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <?php if(null !== ($message = $session->getFlash('success'))): ?>
                        <div class="alert alert-success" role="alert">
                            <h4 class="alert-heading">
                                Well done!
                            </h4>
                            <p>
                                <?php echo $message; ?>
                            </p>
                        </div>
                    <?php elseif(null !== ($message = $session->getFlash('error'))): ?>
                        <div class="alert alert-danger" role="alert">
                            <h4 class="alert-heading">
                                Oh snap!
                            </h4>
                            <p>
                                <?php echo $message; ?>
                            </p>
                        </div>
                    <?php endif; ?>

                    <div data-role="search-not-match" class="row justify-content-center <?php echo ($input->get('q') ? '' : 'hidden'); ?>">
                        <div class="col-md-4 text-center p-3">
                            <img src="assets/img/nopost.png" class="img-fluid">
                            <h3 class="mt-3">Whoops!</h3>
                            <h6 class="text-danger mb-4">No posts match your search.</h6>
                        </div>
                    </div>

                    <?php if (empty($posts)): ?>
                        <?php if(null === $input->get('q')): ?>
                            <div data-role="search-not-found" class="row justify-content-center">
                                <div class="col-md-4 text-center p-3">
                                    <img src="assets/img/nopost.png" class="img-fluid">
                                    <h3 class="mt-3">Whoops!</h3>
                                    <h6 class="text-danger mb-4">
                                        No posts found.
                                    </h6>
                                    <a href="<?php echo base_url('posts/form'); ?>" class="btn btn-primary btn-md">Add New Post</a>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php foreach ($posts as $post): ?>
                            <div class="card rounded-0">
                                <div class="card-body">
                                    <div class="row align-items-center">
                                        <div class="col-10">
                                            <h3 class="card-title mb-2">
                                                <a href="<?php echo base_url('posts/form/' . $post->id); ?>"><?php echo $post->title; ?></a>
                                            </h3>
                                            <h6 class="card-subtitle mb-0">
                                                <span>
                                                    <a href="#">
                                                        <img src="<?php echo $post->user->profile->images->avatar; ?>"
                                                             width="20" class="img-circle">
                                                        <?php echo $post->user->profile->name; ?>
                                                    </a>
                                                </span>
                                                <span><i class="fas fa-clock"></i> <?php echo string_time_elapsed($post->record_create_timestamp); ?></span>
                                            </h6>
                                        </div>
                                        <div class="col-2 text-right">
                                            <div class="dropdown show">
                                                <a class="btn btn-dark btn-link dropdown-toggle custom-dropdown-toggle"
                                                   href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                                                   aria-haspopup="true" aria-expanded="false">

                                                </a>

                                                <?php if($input->get('status') === 'TRASH'): ?>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/restore/' . $post->id); ?>">
                                                            <i class="fa fa-trash text-muted"></i>
                                                            Restore
                                                        </a>
                                                        <div class="dropdown-divider"></div>
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/delete/' . $post->id); ?>" data-action="post-delete" data-id="<?php echo $post->id; ?>">
                                                            <i class="fa fa-trash text-muted"></i>
                                                            Delete
                                                        </a>
                                                    </div>
                                                <?php elseif($input->get('status') === 'DRAFT'): ?>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/form/' . $post->id ); ?>">
                                                            <i class="fas fa-pencil-alt text-muted"></i>
                                                            Edit
                                                        </a>
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/publish/' . $post->id ); ?>">
                                                            <i class="fa fa-eye text-muted"></i>
                                                            Publish
                                                        </a>
                                                        <div class="dropdown-divider"></div>
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/trash/' . $post->id); ?>" data-action="post-delete" data-id="<?php echo $post->id; ?>">
                                                            <i class="fa fa-trash text-muted"></i>
                                                            Trash
                                                        </a>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/form/' . $post->id ); ?>">
                                                            <i class="fas fa-pencil-alt text-muted"></i>
                                                            Edit
                                                        </a>
                                                        <a class="dropdown-item" href="<?php echo domain_url($post->segments); ?>">
                                                            <i class="fa fa-eye text-muted"></i>
                                                            View
                                                        </a>
                                                        <a class="dropdown-item" href="#">
                                                            <i class="fas fa-chart-bar text-muted"></i>
                                                            Stats
                                                        </a>
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/form/', ['copy' => $post->id] ); ?>">
                                                            <i class="fa fa-copy text-muted"></i>
                                                            Copy
                                                        </a>
                                                        <div class="dropdown-divider"></div>
                                                        <a class="dropdown-item" href="<?php echo base_url('posts/trash/' . $post->id); ?>" data-action="post-delete" data-id="<?php echo $post->id; ?>">
                                                            <i class="fa fa-trash text-muted"></i>
                                                            Trash
                                                        </a>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <?php echo $pagination; ?>

                        <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirm-dialog" aria-hidden="true" id="confirm-dialog">
                            <div class="modal-dialog modal-sm" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Confirm</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure, you want to delete this post?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" value="yes">Yes</button>
                                        <button type="button" class="btn btn-primary" value="no">No</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>

    </div>
</div>