<div class="page-schedules">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="card">
                    <div class="card-header">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-md-4">
                                <h5 class="mb-0"><?php echo $page->title ?></h5>
                            </div>
                            <div class="col-md-6">
                                <form method="GET" action="<?php current_url() ?>">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><?php echo $language->getLine('PERIOD'); ?></span>
                                        </div>
                                        <label for="month" class="sr-only"></label>
                                        <select id="month" name="brands" class="form-control custom-select">
                                            <?php if($months):?>
                                                <?php foreach ($months as $key => $value):?>
                                                    <option value="<?=$key;?>"><?=$value;?></option>
                                                <?php endforeach ;?>
                                            <?php endif ;?>
                                        </select>
                                        <label for="years" class="sr-only"></label>
                                        <select id="years" name="entries" class="form-control custom-select">
                                            <?php if($years):?>
                                                <?php foreach ($years as $key => $value):?>
                                                    <option value="<?=$key;?>"><?=$value;?></option>
                                                <?php endforeach ;?>
                                            <?php endif ;?>
                                        </select>
                                        <div class="input-group-prepend">
                                            <button class="btn btn-primary"><?php echo $language->getLine('BTN_GO'); ?></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-calendar"></i>
                                </div>
                                <div class="num text-info">2 Days</div>
                                <h3 class="text-muted" id="work-days"><?php echo $language->getLine('WORK_DAYS'); ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-clock"></i>
                                </div>
                                <div class="num text-info">0</div>
                                <h3 class="text-muted" id="h3"><?php echo $language->getLine('TIME'); ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-clock"></i>
                                </div>
                                <div class="num text-info">840</div>
                                <h3 class="text-muted" id="overtime"><?php echo $language->getLine('OVERTIME'); ?></h3>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-plane"></i>
                                </div>
                                <div class="num text-success">0 Days</div>
                                <h3 class="text-muted" id="travel"><?php echo $language->getLine('TRAVEL'); ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-graduation-cap"></i>
                                </div>
                                <div class="num text-success">0 Days</div>
                                <h3 class="text-muted" id="training"><?php echo $language->getLine('TRAINING'); ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-briefcase"></i>
                                </div>
                                <div class="num text-success">0 Days</div>
                                <h3 class="text-muted" id="vacation"><?php echo $language->getLine('VACATION'); ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-plane"></i>
                                </div>
                                <div class="num text-success"> Days</div>
                                <h3 class="text-muted" id="indispose"><?php echo $language->getLine('INDISPOSE'); ?></h3>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-ban"></i>
                                </div>
                                <div class="num text-danger">0 Days</div>
                                <h3 class="text-muted" id="absent"><?php echo $language->getLine('ABSENT'); ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-clock"></i>
                                </div>
                                <div class="num text-danger">0s</div>
                                <h3 class="text-muted" id="early-leave-time"><?php echo $language->getLine('EARLY_LEAVE_TIME'); ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-widget">
                            <div class="card-body p-3">
                                <div class="icon">
                                    <i class="fas fa-clock"></i>
                                </div>
                                <div class="num text-danger">120</div>
                                <h3 class="text-muted" id="late-time"><?php echo $language->getLine('LATE_TIME'); ?></h3>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body with-table">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead>
                                        <tr>
                                            <th width="13%"><?php echo $language->getLine('DATE'); ?></th>
                                            <th><?php echo $language->getLine('PUNCH_IN'); ?></th>
                                            <th><?php echo $language->getLine('PUNCH_OUT'); ?></th>
                                            <th><?php echo $language->getLine('LATE'); ?></th>
                                            <th><?php echo $language->getLine('DURATION'); ?></th>
                                            <th><?php echo $language->getLine('OVERTIME'); ?></th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">1</span>
                                                <span class="btn btn-outline-success btn-sm">Fri</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">2</span>
                                                <span class="btn btn-outline-success btn-sm">Sat</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">3</span>
                                                <span class="btn btn-outline-success btn-sm">Sun</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">4</span>
                                                <span class="btn btn-outline-success btn-sm">Mon</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">5</span>
                                                <span class="btn btn-outline-success btn-sm">Tue</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">6</span>
                                                <span class="btn btn-outline-success btn-sm">Wed</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">7</span>
                                                <span class="btn btn-outline-success btn-sm">Thu</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">8</span>
                                                <span class="btn btn-outline-success btn-sm">Fri</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">9</span>
                                                <span class="btn btn-outline-success btn-sm">Sat</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">10</span>
                                                <span class="btn btn-outline-success btn-sm">Sun</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">11</span>
                                                <span class="btn btn-outline-success btn-sm">Mon</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">12</span>
                                                <span class="btn btn-outline-success btn-sm">Tue</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">13</span>
                                                <span class="btn btn-outline-success btn-sm">Wed</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">14</span>
                                                <span class="btn btn-outline-success btn-sm">Thu</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">15</span>
                                                <span class="btn btn-outline-success btn-sm">Fri</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">16</span>
                                                <span class="btn btn-outline-success btn-sm">Sat</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">17</span>
                                                <span class="btn btn-outline-success btn-sm">Sun</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">18</span>
                                                <span class="btn btn-outline-success btn-sm">Mon</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">19</span>
                                                <span class="btn btn-outline-success btn-sm">Tue</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">20</span>
                                                <span class="btn btn-outline-success btn-sm">Wed</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">21</span>
                                                <span class="btn btn-outline-success btn-sm">Thu</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">22</span>
                                                <span class="btn btn-outline-success btn-sm">Fri</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">23</span>
                                                <span class="btn btn-outline-success btn-sm">Sat</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">24</span>
                                                <span class="btn btn-outline-success btn-sm">Sun</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">25</span>
                                                <span class="btn btn-outline-success btn-sm">Mon</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">26</span>
                                                <span class="btn btn-outline-success btn-sm">Tue</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">27</span>
                                                <span class="btn btn-outline-success btn-sm">Wed</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr class="table">
                                            <td>
                                                <span class="btn btn-success btn-sm">28</span>
                                                <span class="btn btn-outline-success btn-sm">Thu</span>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
