<div class="page-schedules">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="card">
                    <div class="card-header">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-md-4">
                                <h5 class="mb-0"><?php echo $page->title ?></h5>
                            </div>
                            <div class="col-md-6">
                                <form action="<?= current_url() ?>" method="GET">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><?php echo $language->getLine('PERIOD'); ?></span>
                                        </div>
                                        <label for="entries_year" class="sr-only"></label>
                                        <select id="entries_year" name="entries_month" class="form-control custom-select">
                                            <option><?php echo $language->getLine('SELECT_MONTH'); ?></option>
                                            <?php if($months):?>
                                                <?php foreach ($months as $key => $value):?>
                                                    <option value="<?=$key;?>"
                                                    <?php echo ( $key === $get->month ? 'selected' : '')?>
                                                    ><?=$value;?></option>
                                                <?php endforeach ;?>
                                            <?php endif ;?>
                                        </select>
                                        <label for="entries_year" class="sr-only"></label>
                                        <select id="entries_year" name="entries_year" class="form-control custom-select">
                                            <option><?php echo $language->getLine('SELECT_YEAR'); ?></option>
                                            <?php if($years):?>
                                                <?php foreach ($years as $key => $value):?>
                                                    <option value="<?=$key;?>"
                                                        <?php echo ( $key === $get->year ? 'selected' : '')?>
                                                    ><?=$value;?></option>
                                                <?php endforeach ;?>
                                            <?php endif ;?>
                                        </select>
                                        <label for="entries_year" class="sr-only"></label>
                                        <select id="entries_year" name="entries_year" class="form-control custom-select">
                                            <option><?php echo $language->getLine('SELECT_WEEK'); ?></option>
                                            <?php foreach($weeks as $key => $value):?>
                                                <option value="<?=$value;?>"
                                                    <?php echo ( $key === $get->week ? 'selected' : '')?>
                                                ><?=$value;?></option>
                                            <?php endforeach ;?>
                                        </select>
                                        <div class="input-group-prepend">
                                            <button class="btn btn-primary"><?php echo $language->getLine('BTN_GO'); ?></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php if ($employee): ?>
                <div class="col-lg-10 d-flex flex-wrap">
                    <div class="form-group">
                        <div class="input-group mr-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <?php echo $language->getLine('DAY'); ?>
                                </div>
                            </div>
                            <span class="btn btn-default">
                                       <?=globals()->company->shift->day_start;?>-
                                       <?=globals()->company->shift->day_end;?>
                                    </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group mr-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <?php echo $language->getLine('SWING'); ?>
                                </div>
                            </div>
                            <span class="btn btn-default">
                                       <?=globals()->company->shift->swing_start;?>-
                                       <?=globals()->company->shift->swing_end;?>
                                    </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group mr-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <?php echo $language->getLine('NIGHT'); ?>
                                </div>
                            </div>
                            <span class="btn btn-default">
                                         <?=globals()->company->shift->night_start;?>-
                                       <?=globals()->company->shift->night_end;?>
                                    </span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10">

                    <div class="with-table">
                        <div class="card table-responsive">
                            <table class="card-body table table-bordered table-schedule">
                                <tbody>
                                <tr class="table-info">
                                    <th>Sun</th>
                                    <th>Mon</th>
                                    <th>Tue</th>
                                    <th>Wed</th>
                                    <th>Thu</th>
                                    <th>Fri</th>
                                    <th>Sat</th>
                                </tr>
                                <tr>
                                    <?php if(count($employee->designation)):?>
                                        <?php if($employee->designation->shifts):?>
                                            <?php foreach ($employee->designation->shifts as $shift):?>
                                                <td>
                                                    <select name="" class="form-control custom-select">
                                                        <option><?=$shift->shift;?></option>
                                                    </select>
                                                </td>
                                            <?php endforeach ;?>
                                        <?php endif;?>
                                    <?php endif ;?>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php else: ?>

                <div class="col-lg-10 text-center p-3">
                    <img alt="n" src="{{images_url('default/no-image.jpg')}}" class="img-fluid">
                    <h3 class="mt-3"><?php echo $language->getLine('ALERT_DATA_EMPTY_HEADING'); ?></h3>
                    <h6 class="text-danger mb-4">
                        <?php echo $language->getLine('ALERT_DATA_EMPTY_MESSAGE'); ?>
                    </h6>
                </div>

            <?php endif; ?>
        </div>
    </div>
</div>