<!-- Sidebar scroll-->
<div class="sidebar-scroll">
    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
        <ul id="sidebar-navigation" class="in">
            {{$menus->main->items}}

            {{$menus->manage}}
            {{$menus->manage->items}}

            {{$menus->personalize}}
            {{$menus->personalize->items}}

            {{$menus->configure}}
            {{$menus->configure->items}}
        </ul>
    </nav>
    <!-- End Sidebar navigation -->
</div>
<!-- End Sidebar scroll-->