<div class="card">
    <div class="card-header">
        <h3 class="mb-0">Folder Permissions</h3>
    </div>
    <div class="card-body with-table">
        <div class="table-responsive">
            <table class="table table-bordered table-striped mb-0">
                <thead>
                <tr>
                    <th>Folder</th>
                    <th>Permissions</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach( $folderPermissions as $folder => $permission ): ?>
                    <tr>
                        <td><?php echo $folder; ?></td>
                        <td>
                            <?php if( $permission === true ): ?>
                                <span class="badge badge-success">writable</span>
                            <?php else: ?>
                                <span class="badge badge-danger">not-writable</span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>