<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light page-navbar bg-white p-relative">
                    <button type="button" class="btn btn-default navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbar-22" aria-controls="navbar-22" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-22">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a href="{{base_url('system/information')}}" class="nav-link">Information</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('system/folder-permissions')}}" class="nav-link">Folder Permissions</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('system/php-settings')}}" class="nav-link">PHP Settings</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('system/php-info')}}" class="nav-link">PHP Info</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {{$page->content}}
            </div>
        </div>
    </div>
</div>