<div class="card">
    <div class="card-header">
        <h3 class="mb-0">PHP Settings</h3>
    </div>
    <div class="card-body with-table">
        <div class="table-responsive">
            <table class="table table-bordered table-striped mb-0">
                <thead>
                <tr>
                    <th>Item</th>
                    <th>Global</th>
                    <th>Local</th>
                    <th>Access</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach( $phpSettings as $item => $phpSetting ): ?>
                    <tr>
                        <td><?php echo $item; ?></td>
                        <td><?php echo $phpSetting['global_value']; ?></td>
                        <td><?php echo $phpSetting['local_value']; ?></td>
                        <td><?php echo $phpSetting['access']; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>