<div class="page-administrator">
    <div class="container-fluid">
        <form>
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10">
                    <div class="card">
                        <div class="card-header d-flex flex-wrap align-items-center justify-content-between p-0">
                            <div class="nav-pages">    
                                <ul class="nav" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="tab" href="#user-account" role="tab" aria-controls="user-account" aria-selected="true">
	                                        <?=language('ACCOUNT')?>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#user-identity" role="tab" aria-controls="user-identity" aria-selected="false">
	                                        <?=language('PROFILE')?>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#user-access" role="tab" aria-controls="user-access" aria-selected="false">
	                                        <?=language('AUTHORITIES')?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-options px-3">
                                <button type="button" class="btn btn-default" data-action="cancel">
                                    Cancel                                
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    Save                                
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="tab-content p-0 border-0 mb-0">
                                <div class="tab-pane active" id="user-account" role="tabpanel" aria-labelledby="user-account">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Access</label>
                                                <select name="id_sys_module_user_role" class="form-control custom-select">
                                                    <option value="8" selected="">
                                                        Administrator                                            
                                                    </option>
                                                    <option value="9">
                                                        User                                            
                                                    </option>             
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Groups</label>
                                                <select name="id_sys_module_user_role" class="form-control custom-select">
                                                    <option value="8" selected="">
                                                        Marketing                                            
                                                    </option>
                                                    <option value="9">
                                                        HRD                                            
                                                    </option>             
                                                </select>
                                            </div>
                                        </div>
            
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="id_sys_module_user_role">Status</label>
                                                <select id="id_sys_module_user_role" name="id_sys_module_user_role" class="form-control custom-select">
                                                    <option value="8" selected="">
                                                        Enabled                                            
                                                    </option>
                                                    <option value="9">
                                                        Disabled                                            
                                                    </option>             
                                                </select>
                                            </div>
                                        </div>
            
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Email</label>
                                                <input class="form-control" type="email" name="password" value="">
                                            </div>
                                        </div>
            
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Password</label>
                                                <input class="form-control" type="password" name="password" value="">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Confirm Password</label>
                                                <input class="form-control" type="password" name="password_confirm" value="">
                                            </div>
                                        </div>
            
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Interface Language</label>
                                                <select name="id_sys_module_user_role" class="form-control custom-select">
                                                    <option value="8" selected="">
                                                        English                                            
                                                    </option>
                                                    <option value="9">
                                                        Indonesia                                            
                                                    </option>             
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Content Language</label>
                                                <select name="id_sys_module_user_role" class="form-control custom-select">
                                                    <option value="8" selected="">
                                                        English                                            
                                                    </option>
                                                    <option value="9">
                                                        Indonesia                                            
                                                    </option>             
                                                </select>
                                            </div>
                                        </div>
            
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Extra Info</label>
                                                <textarea name="" id="" class="form-control"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="user-identity" role="tabpanel" aria-labelledby="user-identity">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <input name="photo" type="file" class="dropify" data-height="140" data-default-file="" data-allowed-file-extensions="jpg png">
                                            </div>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Name</label>
                                                        <input class="form-control" type="text" name="name" value="Eddy Dharma" required="">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Username</label>
                                                        <input class="form-control" type="text" name="username" value="restumulya" readonly="">
                                                    </div>
                                                </div>
                                                
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Gender</label>
                                                        <input class="form-control" type="password" name="password" value="">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Mobile</label>
                                                        <input class="form-control" type="text" name="" value="">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Birth Place</label>
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Birth Date</label>
                                                <input type="text" class="form-control datepicker-autoclose">
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Country</label>
                                                <select name="id_sys_module_user_role" class="form-control select-with-search">
                                                    <option value="8" selected="">
                                                        Indonesia                                            
                                                    </option>           
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>State</label>
                                                <select name="id_sys_module_user_role" class="form-control select-with-search">
                                                    <option value="8" selected="">
                                                        Jawa Barat                                            
                                                    </option>           
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>City</label>
                                                <select name="id_sys_module_user_role" class="form-control select-with-search">
                                                    <option value="8" selected="">
                                                        Bandung                                            
                                                    </option>           
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Postal Code</label>
                                                <input type="number" class="form-control">
                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Address</label>
                                                <textarea name="" id="" class="form-control"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="user-access" role="tabpanel" aria-labelledby="user-access">
                                    <div class="user-access">
                                        <div class="card">
                                            <div class="card-header d-flex align-items-center justify-content-between">
                                                <div class="item d-flex align-items-center">
                                                    <label class="switch mr-3">
                                                        <input type="checkbox" checked=""><span></span> 
                                                    </label>
                                                    <p>Blog Posts</p>
                                                </div>
                                                <div class="action d-flex align-items-center">
                                                    <button type="button" class="btn btn-default btn-sm mr-2" data-toggle="collapse" data-target="#method-1">Method</button>
                                                    <select class="select-dropdown" multiple data-style="btn-primary btn-sm" title="Previleges" data-width="fit">
                                                        <option>Create</option>
                                                        <option>Read</option>
                                                        <option>Update</option>
                                                        <option>Delete</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="card-body collapse" id="method-1">
                                                <div class="method-item">
                                                    <div class="item d-flex align-items-center">
                                                        <label class="switch mr-3">
                                                            <input type="checkbox" checked=""><span></span> 
                                                        </label>
                                                        <p>Preview</p>
                                                    </div>
                                                    <div class="action d-flex align-items-center">
                                                        <select class="select-dropdown" multiple data-style="btn-primary btn-sm" title="Previleges" data-width="fit">
                                                            <option>Create</option>
                                                            <option>Read</option>
                                                            <option>Update</option>
                                                            <option>Delete</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                
                                                <div class="method-item">
                                                    <div class="item d-flex align-items-center">
                                                        <label class="switch mr-3">
                                                            <input type="checkbox" checked=""><span></span> 
                                                        </label>
                                                        <p>Domain Tools</p>
                                                    </div>
                                                    <div class="action d-flex align-items-center">
                                                        <select class="select-dropdown" multiple data-style="btn-primary btn-sm" title="Previleges" data-width="fit">
                                                            <option>Create</option>
                                                            <option>Read</option>
                                                            <option>Update</option>
                                                            <option>Delete</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="card">
                                            <div class="card-header d-flex align-items-center justify-content-between">
                                                <div class="item d-flex align-items-center">
                                                    <label class="switch mr-3">
                                                        <input type="checkbox" checked=""><span></span> 
                                                    </label>
                                                    <p>Blog Posts</p>
                                                </div>
                                                <div class="action d-flex align-items-center">
                                                    <button type="button" class="btn btn-default btn-sm mr-2" data-toggle="collapse" data-target="#method-2">Method</button>
                                                    <select class="select-dropdown" multiple data-style="btn-primary btn-sm" title="Previleges" data-width="fit">
                                                        <option>Create</option>
                                                        <option>Read</option>
                                                        <option>Update</option>
                                                        <option>Delete</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="card-body collapse" id="method-2">
                                                <div class="method-item">
                                                    <div class="item d-flex align-items-center">
                                                        <label class="switch mr-3">
                                                            <input type="checkbox" checked=""><span></span> 
                                                        </label>
                                                        <p>Preview</p>
                                                    </div>
                                                    <div class="action d-flex align-items-center">
                                                        <select class="select-dropdown" multiple data-style="btn-primary btn-sm" title="Previleges" data-width="fit">
                                                            <option>Create</option>
                                                            <option>Read</option>
                                                            <option>Update</option>
                                                            <option>Delete</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                
                                                <div class="method-item">
                                                    <div class="item d-flex align-items-center">
                                                        <label class="switch mr-3">
                                                            <input type="checkbox" checked=""><span></span> 
                                                        </label>
                                                        <p>Domain Tools</p>
                                                    </div>
                                                    <div class="action d-flex align-items-center">
                                                        <select class="select-dropdown" multiple data-style="btn-primary btn-sm" title="Previleges" data-width="fit">
                                                            <option>Create</option>
                                                            <option>Read</option>
                                                            <option>Update</option>
                                                            <option>Delete</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>