<div class="row justify-content-center post-editor">
    <div class="col-md-8">
        <div class="form-group mb-0">
            <input type="hidden" name="id" value="">
            <input class="form-control editor-title p-0" type="text" name="title" value="" placeholder="Title" required>
        </div>
        <div class="form-group">
            <div class="editor-slug">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text px-0 text-muted">
                            <i class="fas fa-link"></i>&nbsp;
                            http://yourdomain.com/
                        </span>
                    </div>
                    <input class="form-control pl-0" name="segments" value="<?php echo $page->segments; ?>" type="text" required>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div name="content" class="tinymce-inline">Write your content here...</div>
        </div>
    </div>
</div>

<a class="editor-sidebar-toggle" href="javascript:void(0);"><i class="fa fa-cogs"></i></a>
<div class="right-sidebar">
    <div class="top-title">
        <h6>Page Settings</h6>
        <a href="javascript:void" class="rightside-toggle"><i class="fa fa-times"></i></a>
    </div>

    <div class="sidebar-scroll">
        <div id="settings" role="tablist">
            <div class="card">
                <div class="card-header" role="tab" id="settings-language" class="collapsed" data-toggle="collapse"
                     href="#language" aria-expanded="false" aria-controls="collapse-settings-record-status">
                    <h5 class="mb-0">
                        <a role="button">
                            Language
                        </a>
                    </h5>
                </div>

                <div id="language" class="collapse" role="tabpanel" aria-labelledby="settings-language"
                     data-parent="#language">
                    <div class="card-body">
                        <div class="form-group">
                            <select class="custom-select form-control">
                                <option>English</option>
                                <option>Indonesia</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" role="tab" id="settings-record-status" class="collapsed" data-toggle="collapse"
                     href="#status" aria-expanded="false" aria-controls="collapse-settings-record-status">
                    <h5 class="mb-0">
                        <a role="button">
                            Status
                        </a>
                    </h5>
                </div>

                <div id="status" class="collapse" role="tabpanel" aria-labelledby="settings-record-status"
                     data-parent="#settings">
                    <div class="card-body">
                        <div class="form-group">
                            <select class="custom-select form-control">
                                <option>Publish</option>
                                <option>Draft</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Visibility</label>
                            <select class="custom-select form-control">
                                <option>Public</option>
                                <option>Private</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" role="tab" id="settings-featured-image" class="collapsed" data-toggle="collapse"
                     href="#featured-image" aria-expanded="false" aria-controls="collapse-settings-featured-image">
                    <h5 class="mb-0">
                        <a role="button">
                            Featured Image
                        </a>
                    </h5>
                </div>
                <div id="featured-image" class="collapse" role="tabpanel" aria-labelledby="settings-featured-image"
                     data-parent="#settings">
                    <div class="card-body">
                        <button data-action="media-modal" class="btn btn-default" type="button">Browse</button>
                        <input type="file" name="file-image" class="dropify" data-height="150"
                               data-allowed-file-extensions="gif jpg png" data-default-file=""/>
                    </div>
                    <input type="hidden" name="image" value="">
                </div>
            </div>
            <div class="card">
                <div class="card-header" role="tab" id="settings-search-engine-optimization" class="collapsed" data-toggle="collapse"
                     href="#search-engine-optimization" aria-expanded="false" aria-controls="collapse-settings-search-engine-optimization">
                    <h5 class="mb-0">
                        <a role="button">
                            Search Engine Optimization
                        </a>
                    </h5>
                </div>
                <div id="search-engine-optimization" class="collapse" role="tabpanel" aria-labelledby="settings-search-engine-optimization"
                     data-parent="#settings">
                    <div class="card-body">
                        <div class="form-group">
                            <label>Metarobot</label>
                            <input class="form-control" name="meta[robot]" value="" type="text">
                        </div>
                        <div class="form-group">
                            <label>Metatitle</label>
                            <input class="form-control" name="meta[title]" value="" type="text">
                        </div>
                        <div class="form-group">
                            <label>Metadescription</label>
                            <textarea class="form-control" cols="5" name="meta[description]"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Metakeywords</label>
                            <input class="tagsinput form-control" name="meta[keywords]" value="" data-role="tagsinput" value="" type="text">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
