<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                Title
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-12">
                        <input class="form-control" type="text" name="" value="" placeholder="">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-12">
                        <div class="input-group">
                            <span class="input-group-addon">http://sample.com/</span>
                            <input disabled="disabled" class="form-control disabled" name="alias" value="" type="text">
                            <span data-action="edit-alias" class="input-group-addon"> <i class="fa fa-pencil"></i> </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                Description
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-12">
                        <textarea class="form-control tinymce-full"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                Images
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-12 dropzone" id="dropzone-wrap">
                        <div class="fallback">
                            <input name="file" type="file" multiple />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="dze_info" class="hidden">
            <div class="card">
                <div class="card-header">
                    Uploaded Files Info
                </div>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th width="40%">File name</th>
                            <th width="15%">Size</th>
                            <th width="15%">Type</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4"></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                Search Engine Optimization
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <label class="col-md-3 control-label" for="field-1">Metarobot</label>
                    <div class="col-md-9">
                        <select class="form-control custom-select" name="meta_title">
                            <option value="sightseeing">None </option>
                            <option value="sightseeing">No ODP </option>
                            <option value="sightseeing">No YDIR </option>
                            <option value="sightseeing">No Archive </option>
                            <option value="sightseeing">No Snippet </option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3 control-label" for="field-1">Metatitle</label>
                    <div class="col-md-9">
                        <input class="form-control" name="meta_title" value="" type="text">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3 control-label" for="field-5">Metadescription</label>
                    <div class="col-md-9">
                        <textarea class="form-control" cols="5" name="meta_description"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3 control-label" for="field-5">Metakeywords</label>
                    <div class="col-md-9">
                        <input class="tagsinput form-control" data-role="tagsinput" value="" type="text">
                        <span class="form-text text-muted">Click SEO Meta Help <a href="#" target="_blank">HERE</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>