<div class="page-wrapper">
	<div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light page-navbar bg-white p-relative">
                    <button type="button" class="btn btn-default navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbar-22" aria-controls="navbar-22" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-22">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a href="{{base_url('pages/published')}}" class="nav-link active">Published</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/draft')}}" class="nav-link">Draft</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/scheduled')}}" class="nav-link">Scheduled</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/trash')}}" class="nav-link">Trash</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-primary my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </nav>
            </div>
        </div>
		<div class="product-list">
	        <div class="row">
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/meats.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/fish.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/vegetables.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/frozen.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/package.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/fruits.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/meats.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	            <div class="col-md-3 col-sm-6">
	            	<div class="card card-product">
	            		<div class="card-ribbon">
                            <div class="card-ribbon-container right">
                            	<span class="ribbon ribbon-success"> Special </span>
                            </div>
                        </div>
                        <img src="assets/img/product/fish.jpg" alt="Card image 2" class="card-img-top">
                        <div class="card-badge">
                            <div class="card-badge-container left"> <!-- or add class .right -->
                                <span class="badge badge-default">
                                    Until 2018
                                </span>
                                <span class="badge badge-primary">
                                    20% OFF
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{base_url('products/form')}}">Product Title</a>
                            </h4>
                            <div class="card-price">
                                <span class="discount">Rp. 300.000</span>
                                <span class="reguler">Rp. 200.000</span>
                            </div>
                            <a href="{{base_url('products/form')}}" class="btn btn-block btn-primary">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                        </div>
                    </div>
	            </div>
	        </div>

            <div class="row">
                <div class="col-md-12">
                    <nav>
                        <ul class="pagination d-flex justify-content-center">
                            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Next</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
	    </div>
	</div>
</div>