<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light page-navbar bg-white p-relative">
                    <button type="button" class="btn btn-default navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbar-22" aria-controls="navbar-22" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-22">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a href="{{base_url('')}}" class="nav-link active">All</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('')}}" class="nav-link">Images</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('')}}" class="nav-link">Documents</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('')}}" class="nav-link">Videos</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('')}}" class="nav-link">Audios</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <div class="input-group">
                                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-primary my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex flex-wrap">
                        <div class="btn-group mr-2">
                            <button type="button" class="btn btn-default"><i class="fas fa-image"></i> Add New</button>
                            <button type="button" class="btn btn-default dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Add via URL</a>
                            </div>
                        </div>
                        <div class="btn-action">
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modal-edit">Edit</button>
                            <button type="button" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
        		<div class="media-list">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="media-list-item">
                                <input type="checkbox" name="" id="media1">
                                <label for="media1">
                                    <img src="assets/img/avatar.jpg">
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="media-list-item">
                                <input type="checkbox" name="" id="media2">
                                <label for="media2">
                                    <div class="media-item-file-details">
                                        <div class="media-item-icon">
                                            <i class="fas fa-file-powerpoint"></i>
                                        </div>
                                        <div class="media-item-file-name">
                                            Presentasi yang dibuat makalah
                                        </div>
                                        <div class="media-item-file-extension">
                                            PPTX
                                        </div>
                                    </div>
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="media-list-item uploading">
                                <input type="checkbox" name="" id="media3">
                                <label for="media3">
                                    <img src="assets/img/scheme/scheme1.png">
                                </label>

                                <div class="upload-progress">
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="media-list-item">
                                <input type="checkbox" name="" id="media4">
                                <label for="media4">
                                    <img src="assets/img/cover.jpg">
                                </label>
                            </div>
                        </div>
                    </div>
        	    </div>
            </div>
        </div>

	    <div class="row">
            <div class="col-md-12">
                <nav>
                    <ul class="pagination d-flex justify-content-center">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>
            </div>
        </div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade modal-scroll" id="modal-edit" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalEdit" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <form>
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEdit">Media Edit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="media-editor-wrapper">
                                <img src="assets/img/cover.jpg">
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" class="form-control" name="">
                            </div>
                            <div class="form-group">
                                <label>Caption</label>
                                <textarea class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label>Alt Text</label>
                                <input type="text" class="form-control" name="">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label>URL</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" readonly="">
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-default">Copy</button>
                                    </div>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table file-info">
                                    <tr>
                                        <td width="50%" class="border-0">
                                            <span class="text-muted">File Name</span><br>
                                            bank.jpg
                                        </td>
                                        <td class="border-0">
                                            <span class="text-muted">File Type</span><br>
                                            JPG
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="border-0">
                                            <span class="text-muted">File Dimensions</span><br>
                                            1366 x 1454px
                                        </td>
                                        <td class="border-0">
                                            <span class="text-muted">Upload Date</span><br>
                                            17 April 2018
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>