<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light page-navbar bg-white p-relative">
                    <button type="button" class="btn btn-default navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbar-22" aria-controls="navbar-22" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-22">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a href="{{base_url('pages/published')}}" class="nav-link active">Published</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/draft')}}" class="nav-link">Draft</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/scheduled')}}" class="nav-link">Scheduled</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{base_url('pages/trash')}}" class="nav-link">Trash</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <div class="input-group">
                                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </nav>
            </div>
        </div>
		<div class="row">
		    <div class="col-md-12">
		        <div class="card">
		            <div class="card-header">
		            	<span class="mt-2 d-inline-block">Traffic</span>
		            	<div class="card-options">
		                    <select class="form-control-sm custom-select">
		                        <option>Day</option>
		                        <option>Week</option>
		                        <option>Month</option>
		                        <option>Year</option>
		                    </select>
		                </div>
		            </div>
		            <div class="card-body">
		            	<canvas id="column-chart" height="400"></canvas>
		            </div>
		        </div>
		    </div>
		</div>
		<div class="row">
			<div class="col-md-4">
                <div class="card card-widget">
                    <div class="card-body">
                        <div class="icon"><i class="fa fa-user"></i></div>
                        <div class="num text-muted">2000</div>
                        <h3 class="text-muted">Visitors</h3>
                        <a href="javascript:void(0);" class="info bg-light text-muted">Manage <i class="fa fa-chevron-circle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-widget">
                    <div class="card-body">
                        <div class="icon"><i class="fa fa-eye"></i></div>
                        <div class="num text-muted">1200</div>
                        <h3 class="text-muted">Views</h3>
                        <a href="javascript:void(0);" class="info bg-light text-muted">Manage <i class="fa fa-chevron-circle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-widget">
                    <div class="card-body">
                        <div class="icon"><i class="fa fa-comment"></i></div>
                        <div class="num text-muted">50</div>
                        <h3 class="text-muted">Comments</h3>
                        <a href="javascript:void(0);" class="info bg-light text-muted">Manage <i class="fa fa-chevron-circle-right"></i></a>
                    </div>
                </div>
            </div>
		</div>

		<div class="row">
		    <div class="col-md-4">
		        <div class="card card-widget">
		            <div class="card-body">
		                <div class="icon"> <i class="fa fa-clock-o"></i> </div>
		                <div class="num text-muted">0 Invoice</div>
		                <h3 class="text-muted">Waiting Shipping Charge</h3>
		                <a href="javascript:void(0);" class="info bg-light text-muted" target="_blank">Manage <i class="fa fa-chevron-circle-right"></i></a>
		            </div>
		        </div>
		    </div>
		    <div class="col-md-4">
		        <div class="card card-widget">
		            <div class="card-body">
		                <div class="icon"> <i class="fa fa-refresh"></i> </div>
		                <div class="num text-warning">0 Invoice</div>
		                <h3 class="text-muted">Ordered</h3>
		                <a href="javascript:void(0);" class="info bg-light text-muted" target="_blank">Manage <i class="fa fa-chevron-circle-right"></i></a>
		            </div>
		        </div>
		    </div>
		    <div class="col-md-4">
		        <div class="card card-widget">
		            <div class="card-body">
		                <div class="icon"> <i class="fa fa-ticket"></i> </div>
		                <div class="num text-info">0 Invoice</div>
		                <h3 class="text-muted">Paid</h3>
		                <a href="javascript:void(0);" class="info bg-light text-muted" target="_blank">Manage <i class="fa fa-chevron-circle-right"></i></a>
		            </div>
		        </div>
		    </div>
		</div>

		<div class="row">
		    <div class="col-md-4">
		        <div class="card card-widget">
		            <div class="card-body">
		                <div class="icon"> <i class="fa fa-truck"></i> </div>
		                <div class="num text-info">0 Invoice</div>
		                <h3 class="text-muted">Sent</h3>
		                <a href="javascript:void(0);" class="info bg-light text-muted" target="_blank">Manage <i class="fa fa-chevron-circle-right"></i></a>
		            </div>
		        </div>
		    </div>
		    <div class="col-md-4">
		        <div class="card card-widget">
		            <div class="card-body">
		                <div class="icon"> <i class="fa fa-money"></i> </div>
		                <div class="num text-success">0 Invoice</div>
		                <h3 class="text-muted">Closed</h3>
		                <a href="javascript:void(0);" class="info bg-light text-muted" target="_blank">Manage <i class="fa fa-chevron-circle-right"></i></a>
		            </div>
		        </div>
		    </div>
		    <div class="col-md-4">
		        <div class="card card-widget">
		            <div class="card-body">
		                <div class="icon"> <i class="fa fa-bomb"></i> </div>
		                <div class="num text-danger">0 Invoice</div>
		                <h3 class="text-muted">Expired</h3>
		                <a href="javascript:void(0);" class="info bg-light text-muted" target="_blank">Manage <i class="fa fa-chevron-circle-right"></i></a>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
</div>